"""Create a local review player linked to the real delivery and shot timeline."""
from pathlib import Path
import json

ROOT=Path(__file__).resolve().parents[1]
shots=json.loads((ROOT/'helper/shots.json').read_text())
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OPUS 5.5 · 第一天 — review</title>
<style>*{box-sizing:border-box}body{margin:0;background:#191919;color:#faf9f5;font:16px system-ui,sans-serif}main{max-width:1250px;margin:auto;padding:24px}header{display:flex;align-items:baseline;gap:18px;flex-wrap:wrap}h1{font:600 32px Georgia,serif;margin:0}a{color:#e9a088}p{color:#b0aea5;line-height:1.5}video{width:100%;background:#000;display:block;margin:20px 0 10px;border-radius:6px}#status{font-variant-numeric:tabular-nums;color:#e3dacc;min-height:24px}.controls{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}button{background:#f0eee6;color:#191919;border:0;border-radius:5px;padding:9px 13px;cursor:pointer}button:hover,button.active{background:#d97757;color:#fff}.shots{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:6px}.shots button{text-align:left}.shots small{display:block;opacity:.75;margin-top:3px}details{margin-top:22px}summary{cursor:pointer;color:#e3dacc}</style>
<main><header><h1>OPUS 5.5 · 第一天</h1><a href="../out/opus55_first_day_1080p30.mp4" download>Download movie</a><a href="qa_report.md">QA report</a></header>
<p>43.70 seconds · 1920×1080 · 30 fps · original MP3. Codex-generated artwork with depth, layered cameras and code animation. This player is for reviewing the delivered film; see the report for measured checks and remaining limitations.</p>
<video id="film" controls playsinline preload="metadata" poster="../out/opus55_first_day_poster.jpg" src="../out/opus55_first_day_1080p30.mp4"></video><div id="status">Loading movie metadata…</div>
<div class="controls"><button id="back">← 1 frame</button><button id="next">1 frame →</button><button data-f="339">Stop beat</button><button data-f="359">Birth impact</button><button data-f="1177">Eye pull-out</button><button data-f="1218">Mosaic bridge</button><button data-f="1299">Final hold</button></div>
<details open><summary>52-shot timeline</summary><div id="shots" class="shots"></div></details><p>Frame stepping pauses playback. Browser seeking uses encoded timestamps; the extracted QA images provide exact numbered frames. Native-player and perceptual motion/audio review are separate from automated decoder checks.</p></main>
<script>const shots=__SHOTS__,v=document.querySelector('#film'),status=document.querySelector('#status');function seek(f){v.pause();v.currentTime=(f+.01)/30;}const buttons=[];for(const s of shots){const b=document.createElement('button');b.textContent=s.id;const small=document.createElement('small');small.textContent=`${(s.f0/30).toFixed(2)}s · f${s.f0}–${s.f1-1}`;b.append(small);b.onclick=()=>seek(s.f0);document.querySelector('#shots').append(b);buttons.push(b);}document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>seek(+b.dataset.f));document.querySelector('#back').onclick=()=>seek(Math.max(0,Math.floor(v.currentTime*30+.001)-1));document.querySelector('#next').onclick=()=>seek(Math.min(1310,Math.floor(v.currentTime*30+.001)+1));function update(){const f=Math.min(1310,Math.floor(v.currentTime*30+.001)),i=shots.findIndex(s=>s.f0<=f&&f<s.f1);status.textContent=`${v.currentTime.toFixed(3)} / 43.700 s · frame ${f} · ${shots[i]?.id||''}`;buttons.forEach((b,j)=>b.classList.toggle('active',j===i));}for(const name of ['loadedmetadata','timeupdate','seeked'])v.addEventListener(name,update);v.addEventListener('error',()=>status.textContent='Movie could not be opened. Use the download link or open the MP4 in a local media player.');</script></html>'''
(ROOT/'qa/review.html').write_text(html.replace('__SHOTS__',json.dumps(shots,ensure_ascii=False)))
print(ROOT/'qa/review.html')
