import * as T from'three';import{W,H,canvas,clamp,lerp,ease,spark}from'./util.js';import{overlay,nativeText}from'./text.js';import{Post}from'./post.js';import{Native}from'./native.js';import{particles}from'./particles.js';
const query=new URLSearchParams(location.search),preview=query.has('preview'),lyricOnly=query.has('lyrics');
const renderer=new T.WebGLRenderer({antialias:false,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setSize(W,H);renderer.setPixelRatio(1);renderer.outputColorSpace=T.LinearSRGBColorSpace;renderer.toneMapping=T.NoToneMapping;document.body.appendChild(renderer.domElement);window.__canvas=renderer.domElement;
let gl=renderer.getContext();window.__glInfo={webgl2:gl instanceof WebGL2RenderingContext,maxTexture:gl.getParameter(gl.MAX_TEXTURE_SIZE),renderer:gl.getParameter(gl.RENDERER)};if(!window.__glInfo.webgl2||window.__glInfo.maxTexture<4096)throw Error('WebGL2 probe failed');
const rt=()=>new T.WebGLRenderTarget(W,H,{type:T.HalfFloatType,depthBuffer:true});let sceneRT=rt(),prevRT=rt(),mixRT=rt(),temporalRT=rt();
const accumScene=new T.Scene(),accumCam=new T.Camera(),accumU={tex:{value:null}};let accumMat=new T.ShaderMaterial({uniforms:accumU,transparent:true,depthTest:false,depthWrite:false,blending:T.CustomBlending,blendSrc:T.OneFactor,blendDst:T.OneFactor,vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}`,fragmentShader:`varying vec2 vUv;uniform sampler2D tex;void main(){gl_FragColor=texture2D(tex,vUv)/6.;}`});accumScene.add(new T.Mesh(new T.PlaneGeometry(2,2),accumMat));const post=new Post(renderer);const pre=canvas(),over=canvas(),pc=pre.getContext('2d'),oc=over.getContext('2d');let preTex=new T.CanvasTexture(pre),overTex=new T.CanvasTexture(over);preTex.colorSpace=overTex.colorSpace=T.SRGBColorSpace;
const cache=new Map();async function texture(url){if(cache.has(url)){let v=cache.get(url);cache.delete(url);cache.set(url,v);return v}let res=await fetch(url);if(!res.ok)throw Error('Missing asset '+url);let b=await createImageBitmap(await res.blob(),{imageOrientation:'flipY'}),tex=new T.Texture(b);tex.flipY=false;tex.colorSpace=T.SRGBColorSpace;tex.generateMipmaps=false;tex.minFilter=tex.magFilter=T.LinearFilter;tex.needsUpdate=true;cache.set(url,tex);while([...cache.keys()].filter(k=>k.includes("/plates/")).length>12){let[k,v]=[...cache.entries()].find(([k])=>k.includes("/plates/"));cache.delete(k);v.dispose();v.image.close()}return tex}
const flatScene=new T.Scene(),flatCam=new T.Camera();let flatU={map:{value:null},line:{value:null},reveal:{value:2},zoom:{value:1},roll:{value:0},offset:{value:new T.Vector2()},shade:{value:1}};let flat=new T.Mesh(new T.PlaneGeometry(2,2),new T.ShaderMaterial({uniforms:flatU,vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}`,fragmentShader:`varying vec2 vUv;uniform sampler2D map,line;uniform float zoom,roll,reveal,shade;uniform vec2 offset;void main(){vec2 d=(vUv-.5)*vec2(1.7778,1.);d=mat2(cos(roll),-sin(roll),sin(roll),cos(roll))*d;vec2 uv=d/vec2(1.7778,1.)/zoom+.5+offset;uv=clamp(uv,.001,.999);vec3 c=texture2D(map,uv).rgb;if(reveal<=1.2){float p=uv.x*.8+(1.-uv.y)*.2;float m=1.-smoothstep(reveal-.04,reveal+.04,p);c=mix(texture2D(line,uv).rgb,c,m);c+=vec3(.85,.47,.34)*exp(-pow((p-reveal)*75.,2.))*.6;}gl_FragColor=vec4(c*shade,1.);}`}));flatScene.add(flat);
const pScene=new T.Scene(),pCam=new T.PerspectiveCamera(45,16/9,.01,100);let pu={color:{value:null},depth:{value:null},amount:{value:1.5}};let plane=new T.Mesh(new T.PlaneGeometry(20,11.25,256,144),new T.ShaderMaterial({uniforms:pu,side:T.DoubleSide,vertexShader:`varying vec2 vUv;uniform sampler2D depth;uniform float amount;void main(){vUv=uv;vec3 p=position;p.z+=(texture2D(depth,uv).r-.5)*amount;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`varying vec2 vUv;uniform sampler2D color;void main(){gl_FragColor=texture2D(color,vUv);}`}));pScene.add(plane);
let native,lyricParticles,shots,audio,lines;
function timeHold(t){for(let x of[25.4,28.8,34.78,38,40.2,40.8]){let f=Math.round(x*30)/30;if(t>=f&&t<f+.1)return f;}return t}
const pathData={S03b:[[-.45,0,10.5],[.4,.1,9.5],0,.209],S03c:[[0,0,10],[.4,-.15,7.7],0,.349],S04c:[[0,0,9.3],[2,1.4,2],0,.03],S05:[[0,0,10.7],[0,0,10.6],0,0],S07b:[[.5,-.4,3.2],[0,1,9.7],.04,0],S11c:[[0,-.4,10.2],[0,1.4,8.8],-.12,.12],S13a:[[-7.5,0,7.5],[7.5,0,7.5],-.08,.12],S13b:[[-3,.4,9],[3,-.3,8.2],-.2,.2],S13c:[[0,0,10],[.1,.2,9],.05,-.05],S13d:[[0,0,10],[0,.3,6.8],0,.08]};
async function drawShot(s,t,target){let u=clamp((t-s.start)/(s.end-s.start)),id=s.id;renderer.setRenderTarget(target);renderer.setClearColor(t<11.92?0x141413:0xfaf9f5);renderer.clear();if(lyricOnly)return;
 if(s.source==='H'&&id!=='S03d'){renderer.setRenderTarget(target);renderer.setClearColor(0x000000);renderer.clear();for(let sample=0;sample<6;sample++){let tt=t+(sample/6-.5)*.5/30;native.render(id,tt,audio.envelope[Math.floor(t*30)]||0,temporalRT);accumU.tex.value=temporalRT.texture;renderer.setRenderTarget(target);renderer.autoClear=false;renderer.render(accumScene,accumCam);renderer.autoClear=true;}return}
 let key=id==='S03d'?'S03c':id==='S09b'?'S09b_color':id;let isPlate=s.source==='V'&&!preview;let url=isPlate?`../plates/${id}/${String(Math.max(0,Math.min(s.end_frame-s.start_frame-1,Math.round(t*30)-s.start_frame))).padStart(5,'0')}.jpg`:`../assets/keyframes/${key}.png`;let tex=await texture(url);
 if(s.source.includes('P')&&id!=='S09b'){pu.color.value=tex;try{pu.depth.value=await texture(`../assets/depth/${id}.png`)}catch(e){if(!preview)throw e;pu.depth.value=tex;pu.amount.value=0}let p=pathData[id]||[[0,0,10],[.2,.1,9.5],0,.05],e=id==='S04c'?ease.inExpo(u):ease.inOutCubic(u);let curve=new T.CatmullRomCurve3([new T.Vector3(...p[0]),new T.Vector3(...p[0]).lerp(new T.Vector3(...p[1]),.45),new T.Vector3(...p[1])]);pCam.position.copy(curve.getPoint(e));if(id==='S13c'){pCam.position.x+=Math.sin(t*50)*.08;pCam.position.y+=Math.sin(t*37)*.1}pCam.lookAt(id==='S04c'?2:0,id==='S04c'?1.4:id==='S07b'?lerp(-.4,1,u):0,0);pCam.rotation.z+=lerp(p[2],p[3],e);pCam.fov=id==='S04c'?lerp(45,30,u):45;pCam.updateProjectionMatrix();flatU.map.value=tex;flatU.line.value=tex;flatU.reveal.value=2;flatU.zoom.value=1;flatU.roll.value=0;flatU.offset.value.set(0,0);flatU.shade.value=1;renderer.setRenderTarget(target);renderer.render(flatScene,flatCam);renderer.clearDepth();renderer.autoClear=false;renderer.render(pScene,pCam);renderer.autoClear=true;return}
 flatU.map.value=tex;flatU.line.value=tex;flatU.reveal.value=2;flatU.zoom.value=1;flatU.roll.value=0;flatU.offset.value.set(0,0);flatU.shade.value=id==='S03d'?.6:1;
 if(id==='S09b'){flatU.line.value=await texture('../assets/keyframes/S09b_line.png');flatU.reveal.value=clamp((t-22)/.6)*1.2;flatU.zoom.value=1.08+.05*u}
 if(id==='S03d')flatU.zoom.value=1.15+.12*u;if(id==='S09a')flatU.offset.value.set(0,-.045*u);
 if(preview&&s.source==='V'){flatU.zoom.value=1.02+.05*u;flatU.roll.value=Math.sin(u*2)*.015;}
 renderer.setRenderTarget(target);renderer.render(flatScene,flatCam);
}
const transScene=new T.Scene(),transCam=new T.Camera();let tu={a:{value:null},b:{value:null},p:{value:0},kind:{value:0}};let trans=new T.Mesh(new T.PlaneGeometry(2,2),new T.ShaderMaterial({uniforms:tu,vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}`,fragmentShader:`varying vec2 vUv;uniform sampler2D a,b;uniform float p,kind;float h(vec2 x){return fract(sin(dot(x,vec2(127.1,311.7)))*43758.5453);}void main(){vec2 uv=vUv;vec3 c;if(kind<.5){vec3 ca=vec3(0.),cb=vec3(0.);for(int i=0;i<24;i++){float d=(float(i)/23.-.5)*sin(p*3.14159)*.15;ca+=texture2D(a,uv+vec2(p*1.2+d,0.)).rgb;cb+=texture2D(b,uv-vec2((1.-p)*1.2-d,0.)).rgb;}c=mix(ca,cb,step(.5,p))/24.;}else if(kind<1.5){vec2 d=(uv-.5)*vec2(1.7778,1.);float ang=atan(d.y,d.x),shape=.55+.45*pow(abs(cos(ang*6.)),12.);float m=1.-smoothstep(shape*p*2.6-.015,shape*p*2.6+.015,length(d));c=mix(texture2D(a,uv).rgb,texture2D(b,uv).rgb,m);}else if(kind<2.5){vec2 qa=(uv-.5)/(1.+p*3.)+.5,qb=(uv-.5)/(.3+.7*p)+.5;c=mix(texture2D(a,qa).rgb,texture2D(b,qb).rgb,smoothstep(.35,.7,p));}else if(kind<3.5){float band=floor(uv.y*28.);float m=step(h(vec2(band,5.)),p);uv.x+=(h(vec2(band,floor(p*12.)))-.5)*sin(p*3.14159)*.08;c=mix(texture2D(a,uv).rgb,texture2D(b,uv).rgb,m);}else{float n=h(floor(uv*100.))*.2+uv.x*.6+uv.y*.2;float m=1.-smoothstep(p-.03,p+.03,n);c=mix(texture2D(a,uv).rgb,texture2D(b,uv).rgb,m);}gl_FragColor=vec4(c,1.);}`}));transScene.add(trans);
let transitions={S01b:[2,6],S03a:[-1,2],S03b:[0,4],S04a:[3,4],S06a:[-1,2],S09b:[1,6],S11a:[-1,2],S11c:[0,4],S12a:[0,4],S13b:[1,4],S13c:[0,4],S13d:[3,4],S14:[-1,2],S16a:[-1,2]};
async function init(){[shots,audio,lines]=await Promise.all(['timeline.json','../assets/audio.json','../assets/lyrics.json'].map(u=>fetch(u).then(r=>r.json())));shots=shots.shots;lines=lines.map(l=>({...l,start:Math.round(l.start*30)/30,end:Math.round(l.end*30)/30}));for(let f of['900 100px Noto','900 100px Newsreader','900 100px JetBrains'])await document.fonts.load(f,'第一天永远那么灿烂我存在Opus5.5');await document.fonts.ready;let c=canvas(900,160),g=c.getContext('2d');g.font='900 100px monospace';let fallback=g.measureText('第一天Opus5.5').width;g.font='900 100px Noto';window.__fontInfo={loaded:document.fonts.check('900 100px Noto'),width:g.measureText('第一天Opus5.5').width,fallback};if(!window.__fontInfo.loaded)throw Error('Font probe failed');native=new Native(renderer);try{native.setSilhouette(await texture('../assets/ref/silhouette.png'))}catch(e){if(!preview)throw e}lyricParticles=particles(60000,'永远那么灿烂',77);lyricParticles.object.material.depthTest=false;window.__ready=true;}
window.renderFrame=async f=>{if(!window.__ready)throw Error('Not ready');let s=shots.find(s=>f>=s.start_frame&&f<s.end_frame);if(!s)throw Error('No shot for frame '+f);let raw=f/30,t=timeHold(raw);await drawShot(s,t,sceneRT);let source=sceneRT,tr=transitions[s.id],elapsed=f-s.start_frame,flash=0;if(tr&&elapsed<tr[1]){if(tr[0]<0)flash=.8*(1-elapsed/tr[1]);else{let prev=shots[shots.indexOf(s)-1];await drawShot(prev,(prev.end_frame-1)/30,prevRT);tu.a.value=prevRT.texture;tu.b.value=sceneRT.texture;tu.p.value=(elapsed+1)/tr[1];tu.kind.value=tr[0];renderer.setRenderTarget(mixRT);renderer.render(transScene,transCam);source=mixRT;}}
 let k=audio.envelope[f]||0;overlay(pc,s,t,k,lines,true);overlay(oc,s,t,k,lines,false);if(s.id==='S03d')nativeText(oc,s.id,t,k);if(s.id==='S16c')nativeText(oc,s.id,t,k);
 if(query.has('debug')){oc.fillStyle='#141413';oc.fillRect(0,0,W,45);oc.fillStyle='#D97757';for(let b of audio.beats){let x=(b-(raw-1))*W/2;if(x>=0&&x<W)oc.fillRect(x,0,3,45)}oc.fillStyle='white';oc.font='25px JetBrains';oc.fillText(`${f} ${s.id} ${raw.toFixed(3)}`,100,32)}
 preTex.needsUpdate=overTex.needsUpdate=true;let act=raw<11.92?1:raw<30.68?2:3;let props={t:s.id==='S05'?11.2:t,kick:k,flash,radial:s.id==='S04c'?.15*clamp((raw-s.start)/(s.end-s.start)):s.id==='S11b'?.06:0,ca:s.id==='S03a'?.15:.015,glitch:['S03a','S04b','S13e'].includes(s.id)?k:0,sat:act===1?.75:act===2?1.05:1.2,exposure:act===1?.65:act===2?1.0:1,warm:s.id.startsWith('S16')?.6:act===2?.25:.15,shock:-1,quiet:s.id==='S05'?1:0,card:s.id==='S16c'?1:0};if(s.id==='S05'){props.sat=.05;props.exposure=.32;}for(let hit of[173/30,358/30,1026/30])if(raw>=hit&&raw<hit+.5)props.shock=(raw-hit)*2.8;
 if(raw>=34.21&&raw<42.45){let l=lines.find(l=>raw>=l.start&&raw<l.end);lyricParticles.u.uT.value=t;lyricParticles.u.uProgress.value=clamp((raw-l.start)/.5);lyricParticles.u.uAlpha.value=.9;lyricParticles.u.uSize.value=1.8;lyricParticles.object.position.set(0,-2.6,1);let ps=new T.Scene();ps.add(lyricParticles.object);let cam=new T.PerspectiveCamera(45,16/9,.1,100);cam.position.z=12;renderer.autoClear=false;renderer.setRenderTarget(source);renderer.render(ps,cam);renderer.autoClear=true;}
 post.render(source,preTex,overTex,props);renderer.getContext().finish();return{id:s.id,frame:f,t:raw};};init().catch(e=>{window.__error=e.stack;console.error(e)});
