import * as T from'three';import{RoomEnvironment}from'three/addons/environments/RoomEnvironment.js';import{RoundedBoxGeometry}from'three/addons/geometries/RoundedBoxGeometry.js';import{canvas,rng,spark,clamp,ease,lerp}from'./util.js';import{particles}from'./particles.js';import{nativeText}from'./text.js';
export class Native{constructor(renderer){this.r=renderer;this.scene=new T.Scene();this.cam=new T.PerspectiveCamera(45,16/9,.01,10000);this.cam.position.z=12;this.sheet=canvas();this.ctx=this.sheet.getContext('2d');this.tex=new T.CanvasTexture(this.sheet);this.tex.colorSpace=T.SRGBColorSpace;this.flat=new T.Mesh(new T.PlaneGeometry(16,9),new T.MeshBasicMaterial({map:this.tex,transparent:true}));this.flat.material.depthTest=false;this.flat.material.depthWrite=false;this.flat.renderOrder=5;this.scene.add(this.flat);this.slab=new T.Mesh(new RoundedBoxGeometry(16,9,.14,4,.18),new T.MeshPhysicalMaterial({color:0x30302d,roughness:.15,metalness:.1,clearcoat:1}));this.scene.add(this.slab);this.pm=new T.PMREMGenerator(renderer);this.scene.environment=this.pm.fromScene(new RoomEnvironment(),.04).texture;this.scene.add(new T.HemisphereLight(0xfaf9f5,0x141413,2));let light=new T.DirectionalLight(0xd97757,3);light.position.set(-4,5,8);this.scene.add(light);
 this.galaxy=particles(800000,'5.5');this.galaxy.u.uMode.value=1;this.scene.add(this.galaxy.object);
 let c=canvas(512,512),g=c.getContext('2d');spark(g,256,256,235,0,'#D97757');this.sun=new T.Mesh(new T.PlaneGeometry(8,8),new T.MeshBasicMaterial({map:new T.CanvasTexture(c),transparent:true,depthWrite:false}));this.sun.material.map.colorSpace=T.SRGBColorSpace;this.sun.material.color.setRGB(2.2,2.2,2.2);this.sun.position.z=.05;this.scene.add(this.sun);
 this.iris=new T.Mesh(new T.PlaneGeometry(24,14),new T.ShaderMaterial({uniforms:{t:{value:0}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec2 vUv;uniform float t;void main(){vec2 d=(vUv-.5)*vec2(1.7778,1.);float r=length(d),a=atan(d.y,d.x);float rays=pow(.5+.5*sin(a*150.+sin(a*19.)*4.),5.);vec3 c=mix(vec3(.08,.07,.06),vec3(.85,.47,.34),smoothstep(.06,.22,r));c*=.6+rays*.7;c*=1.-smoothstep(.4,.49,r);c*=smoothstep(.06,.13,r);gl_FragColor=vec4(c,1.);}`}));this.scene.add(this.iris);
 let atlas=canvas(1024,64),ac=atlas.getContext('2d');ac.fillStyle='#D97757';ac.font='48px JetBrains';ac.textBaseline='middle';let chars='0123456789ΣΩ∂∇AI{}<>/作品';[...chars].forEach((ch,i)=>ac.fillText(ch,i*43,32));let geo=new T.InstancedBufferGeometry();geo.index=new T.PlaneGeometry(.4,.5).index;let base=new T.PlaneGeometry(.4,.5);geo.attributes.position=base.attributes.position;geo.attributes.uv=base.attributes.uv;let rr=rng(9),seeds=new Float32Array(3000*4);for(let i=0;i<seeds.length;i++)seeds[i]=rr();geo.setAttribute('seed',new T.InstancedBufferAttribute(seeds,4));geo.instanceCount=3000;this.glyphs=new T.Mesh(geo,new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{t:{value:0},atlas:{value:new T.CanvasTexture(atlas)}},vertexShader:`attribute vec4 seed;uniform float t;varying vec2 vUv;void main(){vUv=vec2((uv.x+floor(seed.w*23.))/23.,uv.y);vec3 p=position+vec3((seed.x-.5)*30.,(seed.y-.5)*18.,-mod(seed.z*100.-t*(12.+t*3.),100.));gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`uniform sampler2D atlas;varying vec2 vUv;void main(){gl_FragColor=texture2D(atlas,vUv);}`}));this.glyphs.frustumCulled=false;this.scene.add(this.glyphs);
 this.flood=new T.Mesh(new T.PlaneGeometry(100,60),new T.ShaderMaterial({uniforms:{t:{value:0}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec2 vUv;uniform float t;float n(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(n(i),n(i+vec2(1,0)),f.x),mix(n(i+vec2(0,1)),n(i+1.),f.x),f.y);}float fb(vec2 p){float a=.5,s=0.;for(int i=0;i<5;i++){s+=a*noise(p);p=p*2.03+2.;a*=.5;}return s;}void main(){vec2 p=vUv*5.;p+=vec2(fb(p+t*.4),fb(p-t*.3))*3.;float f=fb(p);vec3 c=mix(vec3(.85,.47,.34),vec3(.42,.61,.8),smoothstep(.3,.55,f));c=mix(c,vec3(.47,.55,.36),smoothstep(.57,.7,f));c=mix(c,vec3(.98,.98,.96),smoothstep(.72,.85,f));gl_FragColor=vec4(c,1.);}`}));this.flood.position.z=.02;this.scene.add(this.flood);
 this.crowd=null;this.ground=new T.Mesh(new T.PlaneGeometry(2000,2000),new T.ShaderMaterial({vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec2 vUv;void main(){float d=length(vUv-.5)*2.;vec3 c=mix(vec3(.65,.5,.36),vec3(.18,.15,.13),smoothstep(0.,.9,d));gl_FragColor=vec4(c,1.);}`}));this.ground.rotation.x=-Math.PI/2;this.ground.position.y=-4;this.scene.add(this.ground);
}
setSilhouette(tex){let geo=new T.PlaneGeometry(.6,1.4),m=new T.MeshBasicMaterial({map:tex,transparent:true,alphaTest:.2,opacity:.62,color:0x805038,side:T.DoubleSide});this.crowd=new T.InstancedMesh(geo,m,12000);let d=new T.Object3D();for(let i=0;i<12000;i++){d.position.set((i%120-60)*1.4+Math.sin(i*17)*.25,-3.3,-Math.floor(i/120)*1.6+Math.cos(i*7)*.25);d.updateMatrix();this.crowd.setMatrixAt(i,d.matrix)}this.scene.add(this.crowd)}
render(id,t,kick,rt){let u=id==='S15'?clamp((t-37.07)/2.83):0;this.scene.fog=id==='S15'?new T.FogExp2(0xd4a27f,.018):null;this.scene.background=new T.Color(id==='S16c'?0xfaf9f5:id==='S15'?0x141413:0x141413);for(let o of [this.flat,this.slab,this.galaxy.object,this.sun,this.iris,this.glyphs,this.flood,this.ground,this.crowd])if(o)o.visible=false;this.cam.position.set(0,0,12);this.cam.rotation.set(0,0,0);this.cam.fov=45;this.cam.lookAt(0,0,0);
 if(id==='S15'){this.galaxy.object.visible=u>.48;this.galaxy.u.uT.value=t;this.galaxy.u.uProgress.value=clamp((u-.72)/.2);this.galaxy.u.uAlpha.value=clamp((u-.48)*5);this.galaxy.object.scale.setScalar(lerp(1,3.2,clamp((u-.7)/.25)));this.galaxy.object.rotation.z=u*.349;this.cam.position.z=.7*Math.exp(u*4.);this.cam.rotation.z=u*.349;this.iris.visible=u<.25;this.sun.visible=u<.75;this.sun.scale.setScalar(.24);this.sun.rotation.z=t*.4;if(this.crowd){this.crowd.visible=u>.18&&u<.7;this.crowd.rotation.z=Math.sin(t)*.003}this.ground.visible=u>.18&&u<.7;this.cam.position.y=u>.2&&u<.7?(u-.2)*9:0;this.cam.lookAt(0,0,-u*2);}
 else{nativeText(this.ctx,id,t,kick);this.tex.needsUpdate=true;this.flat.material.needsUpdate=true;this.flat.visible=true;this.flat.position.set(0,0,.09);this.flat.scale.setScalar(1);this.flat.rotation.set(0,0,0);this.cam.position.z=10.87;if(id==='S01a'){this.slab.visible=true;this.cam.position.set(.15,0,9.4+t*1.08);this.cam.rotation.z=t*.037;this.flat.scale.setScalar(.98);this.flat.material.transparent=false;}else this.flat.material.transparent=true;if(id==='S04b'){this.glyphs.visible=true;this.glyphs.material.uniforms.t.value=t-8.24;this.cam.position.z=11.2-(t-9.59)*.3;this.cam.rotation.z=Math.sin(t*6)*.015}if(id==='S13e'){this.flood.visible=true;this.flood.material.uniforms.t.value=t;this.cam.position.x=Math.sin(t*90)*.025*kick;}if(id==='S16c'){this.cam.position.z=10.87-.08*clamp((t-42.45)/.95);}}
 this.cam.updateProjectionMatrix();this.r.setRenderTarget(rt);this.r.render(this.scene,this.cam);}
}
