from pathlib import Path
import json
root=Path(__file__).resolve().parents[3];out=root/'episodes/first-day-mix/production/scene-images.json'
items=[
('go_macro','Extreme macro cinema photograph, 16:9. A glossy black Go stone suspended a centimetre above an ivory porcelain oval with one shallow human sole indentation and a closed hairline seam. This single exquisite object occupies the right third; at left vast warm ivory negative space. Beneath the oval a delicate brass ring bracket, beneath the bracket empty pale blue air, no table or floor. Tiny mechanical ivory folds visible inside seam, cobalt inlay only along its edge. 100mm macro lens at stone height, crisp morning sun from upper left, clean elegant deep shadows, real ceramic and brass, astounding tactile detail at contact point, no text, no letters, no people, no clouds or mountain scenery.'),
('cyber_fan','Widescreen cinema environment for a futuristic music video. A single enormous articulated folding fan is a miniature CYBERPUNK CITY: translucent cobalt circuitlike paper panels with real orange practical lights, tightly layered black mechanical ribs, small cyan phosphor glass windows. The fan is suspended diagonally across deep black air. Camera 24mm from below extremely close to its central brass hinge, strong perspective. Empty oval ring sockets run along its narrow bottom ribs; see darkness cleanly through all rings, no continuous floor. This is an intricate focal architectural mechanism meant to be inspected, but primary silhouette is spare and elegant. One brilliant vermilion illuminated slit, no rain, no magenta haze, no text, no people. Chinese paper theatre meeting modern electronic fabrication, amazing scale.'),
('canopy_detail','Photographic cinematic extreme closeup of an exquisite ivory-and-cobalt paper flying canopy. Visible central brass umbrella-like hub, radial articulated ribs, translucent folded paper catching sunlight from above left. Apricot woven harness lines descend out of frame. Background is pale blue-white empty sky without clouds or mountains. 35mm low camera nearly under the hinge, asymmetrical radial composition, clean tactile materials, intricate mechanical detail is the only focal point. No people, no text or logos, no extra wings, no floor.'),
('future_gate','One impossible architectural showpiece suspended in deep ultramarine black space, widescreen cinematic photograph of a real miniature. A spiral of rectangular ivory folded frames, each elaborately hinged in brass, creates a noncentral vanishing point at right. Frames twist continuously toward a single cobalt pupil-like empty hole. Vermilion light comes from inside one near frame and lights its actual edges. Sparse tiny ivory paper flecks establish enormous scale. 18mm camera from underneath a massive foreground hinge, dramatic near/far depth, no people, no text, no floating mountains, no generic neon tunnel, no luminous binary code. Astonishing precise crafted sculpture, detail concentrated in nearest hinge, great quiet areas.')]
man=[{'id':i,'mode':'t2i','prompt':p,'out':f'work/first-day-mix/production/plates/{i}.png','refs':[],'deps':[]} for i,p in items]
out.write_text(json.dumps(man,indent=2)+'\n')
