from pathlib import Path
import json,hashlib
root=Path(__file__).resolve().parents[3];p=root/'work/first-day-mix/production/motion-test';p.mkdir(parents=True,exist_ok=True)
def sha(x):return hashlib.sha256(x.read_bytes()).hexdigest()
def save(name,data):f=p/name;f.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');return str(f.relative_to(root))
paths={'macro':'work/first-day-mix/production/plates/go_macro.png','night':'work/first-day-mix/art/c5.png'}
story=save('story.json',{'shots':[{'id':x,'asset':x} for x in paths]});assets=save('assets.json',paths)
evidence={'macro':'Inspected full native image: black curved Go stone above ivory seed with shallow sole impression and visible cobalt seam; brass ring lower edge visible; no human occupants; large left negative space. This isolated contact insert deliberately excludes the larger fan beyond close camera. Shape is rounder than a normal Go stone but legible as the fictional trigger.','night':'Inspected C5 at full frame: two cel figures, orange left and violet right, each with complete shoes on individual ivory marked surfaces; wrist connection visible; near/mid empty rings expose black void; narrow brass links attach to giant scroll fan. No continuous floor. This is a representative night duo shot, not evidence of all23slots or full-film occupancy.'}
jud={'stage':'representative independent macro and night motion tests','reviewer':'Codex root visual source inspection','reviewed_visually':True,'status':'approved','scope_note':'Two independent source still tests only, not whole-film continuity or motion approval.','story':story,'assets':assets,'reviewed_input_hashes':{'story':sha(root/story),'assets':sha(root/assets)},'reviewed_sources':[{'path':v,'sha256':sha(root/v),'status':'approved','evidence':evidence[k]} for k,v in paths.items()],'cuts':[{'from_shot':'macro','to_shot':'night','from_asset':'macro','to_asset':'night','relation':'scene_change','status':'approved','issues':[],'evidence':'Independent representative test shots separated by scene and medium, not a proposed continuous cut. Both source compositions have been inspected; no implied shared physical occupancy across this test boundary.'}],'state_changes':[],'additional_inputs':[]}
save('judgments.json',jud)
jobs=[{'id':'macro','shot_id':'macro','image_key':'macro','image':paths['macro'],'endpoint':'i2v','duration':5,'resolution':'1080P','prompt_expansion_mode':'disabled','seed':1031,'out':'work/first-day-mix/production/video/macro.mp4','prompt':'Macro cinema shot. The black Go stone drops softly onto the shallow impression in the ivory ceramic seed, taps once and rebounds a little. At contact the narrow blue seam glows briefly and the ceramic halves part slightly. Beautiful physical ceramic highlights; static macro camera, no background changes, no text, no people. One small impact then settling. No additional objects.'},
{'id':'night','shot_id':'night','image_key':'night','image':paths['night'],'endpoint':'i2v','duration':5,'resolution':'1080P','prompt_expansion_mode':'disabled','seed':1032,'out':'work/first-day-mix/production/video/night.mp4','prompt':'Mixed-media music video: two flat cel adults on separate ivory ceramic pads in the suspended paper-scroll theatre. The orange-clad woman and violet-clad man keep holding wrists, bend knees then make one lively coordinated side-step in place, coats sweeping. The gigantic hinged scroll fan behind them opens ten degrees and its warm practical lamps brighten. Cobalt paper fragments sweep through foreground. Keep both complete bodies and pads, open black air in all empty sockets, no floor, no additional people. Camera makes a short smooth lateral move right, faces composed, mouths closed, not speaking.'}]
save('motion.json',{'continuity_review':'work/first-day-mix/production/motion-test/review.json','jobs':jobs})
