import * as THREE from 'three';
import {makeHalo} from './halo.js';
import {focalFov} from './camera.js';
export class DepthPlate{
 constructor(W,H){this.canvas=document.createElement('canvas');this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:true,preserveDrawingBuffer:true,alpha:false});this.renderer.setSize(W,H,false);this.renderer.setPixelRatio(1);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#141413');this.camera=new THREE.PerspectiveCamera(focalFov(35),W/H,.01,100);this.camera.position.z=10;this.entries=new Map();this.W=W;this.H=H;}
 async load(id,imageURL,depthURL){const loader=new THREE.TextureLoader();let [tex,depth]=await Promise.all([loader.loadAsync(imageURL),loader.loadAsync(depthURL)]);tex.colorSpace=THREE.SRGBColorSpace;tex.anisotropy=8;let c=document.createElement('canvas');c.width=257;c.height=145;let x=c.getContext('2d');x.drawImage(depth.image,0,0,c.width,c.height);let pixels=x.getImageData(0,0,c.width,c.height).data;let geo=new THREE.PlaneGeometry(12,6.75,256,144);let p=geo.attributes.position;for(let i=0;i<p.count;i++){let d=pixels[i*4]/255;p.setZ(i,(d-.5)*1.2);}p.needsUpdate=true;geo.computeVertexNormals();let mesh=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({map:tex,toneMapped:false}));mesh.visible=false;let backing=new THREE.Mesh(new THREE.PlaneGeometry(14.4,8.1),new THREE.MeshBasicMaterial({map:tex,toneMapped:false}));backing.position.z=-.7;backing.visible=false;this.scene.add(backing);mesh.userData.backing=backing;this.scene.add(mesh);mesh.userData.depthPixels=pixels;this.entries.set(id,mesh);depth.dispose();}
 project(id,u,v,size){let m=this.entries.get(id),p=m.geometry.attributes.position;let ix=Math.round(u*256),iy=Math.round(v*144),i=iy*257+ix;let q=new THREE.Vector3(p.getX(i),p.getY(i),p.getZ(i));let z=m.localToWorld(q.clone().add(new THREE.Vector3(size*12,0,0))).project(this.camera);m.localToWorld(q);q.project(this.camera);return[(q.x*.5+.5)*this.W,(-q.y*.5+.5)*this.H,Math.abs(z.x-q.x)*this.W*.5];}
 setScale(id,value){let m=this.entries.get(id);m.scale.setScalar(value);m.userData.backing.scale.setScalar(value);m.userData.backing.position.z=-.7*value;}
 setFrame(id,texture){let m=this.entries.get(id);m.material.map=texture;m.userData.backing.material.map=texture;}
 addHalo(id){const h=makeHalo();h.position.set(0,2.65,.05);h.visible=false;this.scene.add(h);this.entries.get(id).userData.halo=h;}
 render(id,u,{distance=10,focal=35,dx=0,dy=0,roll=0,dollyZoom=false,time=0}={}){for(let[k,m]of this.entries){m.visible=k===id;m.userData.backing.visible=k===id;if(m.userData.halo){m.userData.halo.visible=k===id;m.userData.halo.rotation.z=time*.2;}}let mesh=this.entries.get(id);if(!mesh)throw Error('Missing depth plate '+id);this.camera.position.set(dx,dy,distance);this.camera.up.set(Math.sin(roll),Math.cos(roll),0);this.camera.lookAt(dx*.1,dy*.1,0);this.camera.fov=dollyZoom?THREE.MathUtils.radToDeg(2*Math.atan(6.5/(2*distance))):focalFov(focal);this.camera.updateProjectionMatrix();this.renderer.render(this.scene,this.camera);return this.canvas;}
}
