import * as THREE from 'three';
import {setCamera} from './camera.js';import {vector} from './vectors.js';import {tracked} from './media.js';
const{clamp,smoothstep,easeInOutCubic}=window.RT;
export class HandOrbit{
 constructor(parent){this.parent=parent;this.group=new THREE.Group();parent.scene.add(this.group);this.group.visible=false;}
 async init(){let loader=new THREE.TextureLoader();const names=['S23-v1','S23-90-v1','S23-180-v1','S23-270-v1'];this.maps=await Promise.all(names.map(n=>loader.loadAsync(`/assets/mattes/${n}-refined.png`)));this.depths=await Promise.all(names.map(n=>loader.loadAsync(`/assets/depth/${n}-smooth.png`)));this.depthData=this.depths.map(t=>{let c=document.createElement('canvas');c.width=257;c.height=145;let x=c.getContext('2d');x.drawImage(t.image,0,0,257,145);return x.getImageData(0,0,257,145).data;});for(let t of this.maps){t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;}
 this.lines=await Promise.all(names.map(n=>loader.loadAsync(`/assets/mattes/${n}-line.png`)));for(const t of this.lines)t.colorSpace=THREE.SRGBColorSpace;this.baseFront=this.maps[0];this.uniforms={lineA:{value:this.lines[0]},lineB:{value:this.lines[0]},maskA:{value:this.maps[0]},maskB:{value:this.maps[0]},nextMap:{value:this.maps[0]},depthA:{value:this.depths[0]},depthB:{value:this.depths[0]},viewMix:{value:0},reveal:{value:0},opusSideA:{value:0},opusSideB:{value:0},focus:{value:0}};
 const material=new THREE.MeshBasicMaterial({map:this.maps[0],transparent:true,alphaTest:.015,side:THREE.DoubleSide,premultipliedAlpha:true});material.onBeforeCompile=s=>{Object.assign(s.uniforms,this.uniforms);s.vertexShader='uniform sampler2D depthA,depthB;uniform float viewMix;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','vec3 transformed=vec3(position);float dep=mix(texture2D(depthA,uv).r,texture2D(depthB,uv).r,viewMix);transformed.z+=(dep-.5)*.14;');s.fragmentShader='uniform sampler2D nextMap,depthA,depthB,lineA,lineB,maskA,maskB;uniform float viewMix,reveal,opusSideA,opusSideB,focus;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <map_fragment>',`float dep=mix(texture2D(depthA,vMapUv).r,texture2D(depthB,vMapUv).r,viewMix);float blur=min(.0035,abs(dep-mix(.8,.35,focus))*.006);vec2 dx=vec2(blur,0.),dy=vec2(0.,blur);vec4 colA=(texture2D(map,vMapUv)*4.+texture2D(map,vMapUv+dx)+texture2D(map,vMapUv-dx)+texture2D(map,vMapUv+dy)+texture2D(map,vMapUv-dy))/8.;vec4 colB=(texture2D(nextMap,vMapUv)*4.+texture2D(nextMap,vMapUv+dx)+texture2D(nextMap,vMapUv-dx)+texture2D(nextMap,vMapUv+dy)+texture2D(nextMap,vMapUv-dy))/8.;colA.a=texture2D(maskA,vMapUv).a;colB.a=texture2D(maskB,vMapUv).a;colA.rgb*=colA.a;colB.rgb*=colB.a;vec4 col=mix(colA,colB,viewMix);col.rgb/=max(col.a,.001);float edge=length(texture2D(map,vMapUv+vec2(.001,0.)).rgb-texture2D(map,vMapUv-vec2(.001,0.)).rgb)+length(texture2D(map,vMapUv+vec2(0.,.001)).rgb-texture2D(map,vMapUv-vec2(0.,.001)).rgb);float side=mix(opusSideA,opusSideB,viewMix);float opus=mix(1.-smoothstep(.49,.52,vMapUv.x),smoothstep(.48,.51,vMapUv.x),side);float wave=smoothstep(reveal-.1,reveal,length(vMapUv-vec2(.5,.53)));vec3 line=mix(texture2D(lineA,vMapUv).rgb,texture2D(lineB,vMapUv).rgb,viewMix);col.rgb=mix(col.rgb,line,opus*wave);diffuseColor*=col;`);};
 this.mesh=new THREE.Mesh(new THREE.PlaneGeometry(4.7,4.7*9/16,512,288),material);this.mesh.position.y=1;this.group.add(this.mesh);
 // A fixed room surrounds the orbit; views do not rotate the background with the subjects.
 let wall=new THREE.MeshBasicMaterial({color:'#E8E6DC',side:THREE.BackSide});this.room=new THREE.Mesh(new THREE.BoxGeometry(12,12,12),wall);this.room.position.y=1;this.group.add(this.room);
 let tex=await loader.loadAsync('/assets/environment/apartment.png');tex.colorSpace=THREE.SRGBColorSpace;for(let side=0;side<4;side++){let angle=side*Math.PI/2,wallPlate=new THREE.Mesh(new THREE.PlaneGeometry(12,9),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));wallPlate.position.set(Math.sin(angle)*5.9,1,-Math.cos(angle)*5.9);wallPlate.rotation.y=-angle;this.group.add(wallPlate);}
 let sky=await loader.loadAsync('/assets/plates/cloud-plate-v1.png');sky.colorSpace=THREE.SRGBColorSpace;let window=new THREE.Mesh(new THREE.PlaneGeometry(12,9),new THREE.MeshBasicMaterial({map:sky,side:THREE.DoubleSide}));window.position.set(5.8,1,0);window.rotation.y=-Math.PI/2;this.group.add(window);
 let desk=new THREE.Mesh(new THREE.BoxGeometry(2.5,.12,1.2),new THREE.MeshBasicMaterial({color:'#D4A27F'}));desk.position.set(-3,-.4,-2);this.group.add(desk);
 }
 project(u,v,size){let {i,j,w}=this.viewState,ix=Math.max(0,Math.min(256,Math.round(u*256))),iy=Math.max(0,Math.min(144,Math.round(v*144))),k=(iy*257+ix)*4;let d=(this.depthData[i][k]*(1-w)+this.depthData[j][k]*w)/255,gw=4.7,gh=4.7*9/16,z=(d-.5)*.14;let p=this.mesh.localToWorld(new THREE.Vector3((u-.5)*gw,(.5-v)*gh,z)),q=this.mesh.localToWorld(new THREE.Vector3((u+size-.5)*gw,(.5-v)*gh,z));p.project(this.parent.camera);q.project(this.parent.camera);return[(p.x*.5+.5)*this.parent.W,(-p.y*.5+.5)*this.parent.H,Math.abs(q.x-p.x)*this.parent.W*.5];}
 drawBrand(ctx,logos,t,u){let state=this.viewState,owner=state.w>.5?state.j:state.i;let marks=[{pin:[564,99,40],brooch:[352,443,29],eye0:[430,194,22],eye1:[515,244,22]},null,{pin:[1460,115,35],brooch:[1406,480,34],eye0:[1192,251,26],eye1:[1288,191,26]},{pin:[1400,149,35],brooch:[1328,500,34],eye0:[1134,310,26],eye1:[1255,239,26]}][owner];if(!marks)return;for(let[name,a]of Object.entries(marks)){let tr=owner===0?tracked('S23',name,t):null;let [x,y,size]=this.project(tr?.[0]??a[0]/1672,tr?.[1]??a[1]/941,name.startsWith('eye')?a[2]/1672:(tr?.[2]??a[2]/1672));vector(ctx,name==='brooch'?logos.anthropic:logos.spark,x,y,size,0,name==='brooch'?'#FAF9F5':name.startsWith('eye')?'#141413':u<.2?'#141413':undefined);}}
 render(t,frame,u){let a=-Math.PI*1.5*easeInOutCubic(u);setCamera(this.parent.camera,[Math.sin(a)*2.8,1.07,Math.cos(a)*2.8],[0,1.07,0],24);let v=((a/(Math.PI/2))%4+4)%4,i=Math.floor(v),j=(i+1)%4;this.mesh.material.map=i===0&&this.movieFrame?this.movieFrame:this.maps[i];this.uniforms.nextMap.value=j===0&&this.movieFrame?this.movieFrame:this.maps[j];this.uniforms.maskA.value=this.maps[i];this.uniforms.maskB.value=this.maps[j];this.uniforms.lineA.value=this.lines[i];this.uniforms.lineB.value=this.lines[j];this.uniforms.depthA.value=this.depths[i];this.uniforms.depthB.value=this.depths[j];this.uniforms.viewMix.value=smoothstep(.36,.64,v-i);this.viewState={i,j,w:this.uniforms.viewMix.value};this.uniforms.reveal.value=smoothstep(0,.6,u)*1.5;this.uniforms.opusSideA.value=i>=2?1:0;this.uniforms.opusSideB.value=j>=2?1:0;this.uniforms.focus.value=smoothstep(.75,1,u);this.mesh.lookAt(this.parent.camera.position);this.room.material.color.copy(new THREE.Color('#E8E6DC')).lerp(new THREE.Color('#FFD9A8'),smoothstep(0,.6,u));return this.parent.finish(t,frame);}
}
