import * as THREE from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {ShaderPass} from 'three/addons/postprocessing/ShaderPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {helixPath,setCamera,orbitPath,fpvPath} from './camera.js';
import {vector} from './vectors.js';
import {write} from './text.js';
const{hash01,lerp,clamp,smoothstep,easeInOutCubic}=window.RT;
const V=THREE.Vector3;
function canvasTexture(draw,w=2048,h=2048){let c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'),w,h);let t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t;}
function particleCloud(count){let geo=new THREE.BufferGeometry();let a=new Float32Array(count*3),seeds=new Float32Array(count);for(let i=0;i<count;i++){a[i*3]=(hash01(i,1)-.5)*32;a[i*3+1]=(hash01(i,2)-.5)*20;a[i*3+2]=(hash01(i,3)-.5)*32;seeds[i]=hash01(i,4);}geo.setAttribute('position',new THREE.BufferAttribute(a,3));geo.setAttribute('seed',new THREE.BufferAttribute(seeds,1));let mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0},uStrength:{value:1}},vertexShader:`attribute float seed;uniform float uTime;varying float s;void main(){s=seed;float age=fract((uTime-seed*9.)/7.);vec3 p=position+vec3(sin(seed*36.+uTime*.2),age*3.,cos(seed*21.+uTime*.15));vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=clamp(40./max(1.,-mv.z),1.,8.);}`,fragmentShader:`varying float s;uniform float uStrength;void main(){float d=length(gl_PointCoord-.5)*2.;float a=pow(max(0.,1.-d),3.);gl_FragColor=vec4(mix(vec3(.851,.467,.341),vec3(1.,.85,.66),s)*1.6,a*uStrength);}`});return new THREE.Points(geo,mat);}
function ribbon(index,logo){let geo=new THREE.PlaneGeometry(1,1,160,1);const doc=new DOMParser().parseFromString(logo.raw,'image/svg+xml');const path=doc.querySelector('path');let len=path.getTotalLength();let star=new Float32Array(geo.attributes.position.count*3);for(let i=0;i<geo.attributes.position.count;i++){let u=geo.attributes.uv.getX(i);let pt=path.getPointAtLength((index*.5+u*.5)*len);star.set([-4,(.5-pt.y/94)*15+3,-(pt.x/94-.5)*15],i*3);}geo.setAttribute('aStar',new THREE.BufferAttribute(star,3));geo.setAttribute('aCurve',new THREE.BufferAttribute(new Float32Array(star.length),3));geo.setAttribute('aNormal',new THREE.BufferAttribute(new Float32Array(star.length),3));geo.boundingSphere=new THREE.Sphere(new V(0,1.5,0),20);let mat=new THREE.ShaderMaterial({side:THREE.DoubleSide,transparent:true,depthWrite:true,uniforms:{uTime:{value:0},uProgress:{value:0},uIndex:{value:index}},vertexShader:`attribute vec3 aStar,aCurve,aNormal;uniform float uTime,uProgress,uIndex;varying vec2 vUv;void main(){vUv=uv;float s=uv.x;float th=s*17.+uIndex*3.14159265+uTime*.2;float r=.35+s*9.;vec3 p=aCurve;float width=(.2+1.2*s)*sin(3.14159*uv.x*.95);vec3 normal=aNormal;p=mix(p,aStar,smoothstep(.65,.98,uProgress));p+=normal*(uv.y-.5)*width*2.;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`uniform float uProgress,uIndex,uTime;varying vec2 vUv;vec3 hsv(vec3 c){vec3 p=abs(fract(c.xxx+vec3(0.,.666667,.333333))*6.-3.);return c.z*mix(vec3(1.),clamp(p-1.,0.,1.),c.y);}void main(){float reveal=1.-smoothstep(uProgress-.02,uProgress+.02,vUv.x);float edge=smoothstep(0.,.15,vUv.y)*(1.-smoothstep(.85,1.,vUv.y));vec3 prism=hsv(vec3(fract(vUv.x*.75+(uTime-30.68)*.035),.48,1.));vec3 coral=vec3(.851,.467,.341);if(edge*reveal<.02)discard;gl_FragColor=vec4(pow(mix(coral,prism,.82),vec3(2.2))*.95,edge*reveal*.95);}`});return new THREE.Mesh(geo,mat);}
export class HeroScene{
 constructor(W,H,logos){this.W=W;this.H=H;this.canvas=document.createElement('canvas');this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:true,preserveDrawingBuffer:true,alpha:false});this.renderer.setPixelRatio(1);this.renderer.setSize(W,H,false);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1;this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(45,W/H,.02,500);this.scene.background=new THREE.Color('#6A9BCC');
 let rt=new THREE.WebGLRenderTarget(W,H,{type:THREE.HalfFloatType,samples:4});this.composer=new EffectComposer(this.renderer,rt);this.composer.addPass(new RenderPass(this.scene,this.camera));this.bloom=new UnrealBloomPass(new THREE.Vector2(W,H),.22,.5,.9);this.composer.addPass(this.bloom);
 this.post=new ShaderPass({uniforms:{tDiffuse:{value:null},uTime:{value:0},uFrame:{value:0},uFlash:{value:0},uVignette:{value:0}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform sampler2D tDiffuse;uniform float uTime,uFrame,uFlash,uVignette;varying vec2 vUv;float hash(vec2 p){return fract(sin(dot(p,vec2(12.9898,78.233))+uFrame*17.)*43758.5453);}void main(){vec2 off=(vUv-.5)*uFlash*.003;vec3 c=texture2D(tDiffuse,vUv).rgb;c.r=texture2D(tDiffuse,vUv+off).r;c.b=texture2D(tDiffuse,vUv-off).b;vec3 halo=vec3(0.);for(int i=0;i<8;i++){float a=float(i)*.785398;halo+=max(texture2D(tDiffuse,vUv+vec2(cos(a),sin(a))*.012).rgb-vec3(.8),vec3(0.));}c+=halo*vec3(.024,.008,.005);c*=1.-uVignette*dot(vUv-.5,vUv-.5)*.8;gl_FragColor=vec4(c,1.);}`});this.composer.addPass(this.post);this.composer.addPass(new OutputPass());
 this.world=new THREE.Group();this.scene.add(this.world);this.particles=particleCloud(1400);this.world.add(this.particles);this.ribbons=[ribbon(0,logos.spark),ribbon(1,logos.spark)];this.ribbons.forEach(m=>this.world.add(m));this.ribbonGlow=this.ribbons.map(m=>{let mat=m.material.clone();mat.uniforms=m.material.uniforms;mat.depthWrite=false;mat.blending=THREE.AdditiveBlending;mat.fragmentShader=mat.fragmentShader.replace('*.95,edge*reveal*.95','*2.5,edge*reveal*.18');let glow=new THREE.Mesh(m.geometry,mat);this.world.add(glow);return glow;});
 const st=canvasTexture((x,w,h)=>vector(x,logos.spark,w/2,h/2,w*.98));this.spark=new THREE.Mesh(new THREE.PlaneGeometry(15,15),new THREE.MeshBasicMaterial({map:st,transparent:true,depthWrite:false,color:new THREE.Color(1,.65,.66),side:THREE.DoubleSide}));this.spark.position.set(-4,3,0);this.spark.rotation.y=Math.PI/2;this.world.add(this.spark);
 let ht=canvasTexture((x,w,h)=>{x.translate(w/2,h/2);let text='OPUS 5.5 · OPUS 5.5 · OPUS 5.5 · ';[...text].forEach((s,i)=>{x.save();x.rotate(i/text.length*Math.PI*2);write(x,s,0,-w*.43,w*.047,'#FFD9A8','Lora-SemiBold');x.restore();});});this.halo=new THREE.Mesh(new THREE.PlaneGeometry(3,3),new THREE.MeshBasicMaterial({map:ht,transparent:true,depthWrite:false,side:THREE.DoubleSide,color:new THREE.Color(1.1,1.1,1.1)}));this.halo.rotation.x=-Math.PI/2;this.halo.position.set(0,2.3,0);this.world.add(this.halo);this.haloStart=this.halo.quaternion.clone();const gate=(32-920/30)/(106/30);this.haloGate=new V(...helixPath(gate).position);let dir=new V(...helixPath(gate+.001).position).sub(new V(...helixPath(gate-.001).position)).normalize();let holder=new THREE.Object3D();holder.position.copy(this.haloGate);holder.lookAt(this.haloGate.clone().add(dir));this.haloGateRotation=holder.quaternion.clone();
 let lt=canvasTexture((x,w,h)=>write(x,'第一天的纯真色彩它总是',w/2,h*.65,105,'#FAF9F5'),2048,256);this.lyric=new THREE.Mesh(new THREE.PlaneGeometry(12,1.5),new THREE.MeshBasicMaterial({map:lt,transparent:true,depthWrite:false,side:THREE.DoubleSide}));this.lyric.position.set(-3,1.6,0);this.world.add(this.lyric);this.subjects=[];
 }
 async background(url){const tex=await new THREE.TextureLoader().loadAsync(url);tex.colorSpace=THREE.SRGBColorSpace;this.sky=new THREE.Mesh(new THREE.PlaneGeometry(168,94.5),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide,toneMapped:false}));this.scene.add(this.sky);}
 async addSubject(url,position,height){let tex=await new THREE.TextureLoader().loadAsync(url);tex.colorSpace=THREE.SRGBColorSpace;tex.anisotropy=8;tex.premultiplyAlpha=true;let ratio=tex.image.width/tex.image.height;let mesh=new THREE.Mesh(new THREE.PlaneGeometry(height*ratio,height,256,144),new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:true,alphaTest:.005,side:THREE.DoubleSide,premultipliedAlpha:true}));mesh.position.set(...position);this.world.add(mesh);this.subjects.push(mesh);return mesh;}
 async addViews(urls,position,height){const loader=new THREE.TextureLoader();this.viewTextures=await Promise.all(urls.map(u=>loader.loadAsync(u)));this.baseFront=this.viewTextures[0];for(const t of this.viewTextures){t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;t.premultiplyAlpha=true;}const uniforms={nextMap:{value:this.viewTextures[0]},viewMix:{value:0},bodyTime:{value:0}};const mat=new THREE.MeshBasicMaterial({map:this.viewTextures[0],transparent:true,alphaTest:.005,depthWrite:true,premultipliedAlpha:true,side:THREE.DoubleSide});mat.onBeforeCompile=shader=>{Object.assign(shader.uniforms,uniforms);shader.fragmentShader='uniform sampler2D nextMap;uniform float viewMix;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>','diffuseColor *= mix(texture2D(map,vMapUv),texture2D(nextMap,vMapUv),viewMix);').replace('#include <premultiplied_alpha_fragment>','');shader.vertexShader='uniform float bodyTime;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','vec3 transformed=vec3(position);float hairMask=smoothstep(.18,.42,abs(uv.x-.5))*(1.-smoothstep(.7,.92,uv.y));transformed.x+=sin(bodyTime*2.4+uv.y*7.)*.025*hairMask;');};let mesh=new THREE.Mesh(new THREE.PlaneGeometry(height*1536/1792,height,256,144),mat);mesh.position.set(...position);this.world.add(mesh);this.viewSubject=mesh;this.viewUniforms=uniforms;}
 updateViews(t,theta){if(!this.viewSubject)return;this.viewTextures[0]=this.lipFrame||this.baseFront;let a=((theta/(Math.PI*2))%1+1)%1*4;let i=Math.floor(a),j=(i+1)%4;this.viewSubject.material.map=this.viewTextures[i];this.viewUniforms.nextMap.value=this.viewTextures[j];this.viewUniforms.viewMix.value=smoothstep(0,1,a-i);this.viewState={i,j,w:this.viewUniforms.viewMix.value};this.viewUniforms.bodyTime.value=Math.floor(t*15)/15;this.viewSubject.lookAt(this.camera.position);}
 projectSubject(u,v,size){const m=this.viewSubject,w=m.geometry.parameters.width,h=m.geometry.parameters.height;let p=m.localToWorld(new V((u-.5)*w,(.5-v)*h,.002)),q=m.localToWorld(new V((u+size-.5)*w,(.5-v)*h,.002)),up=m.localToWorld(new V((u-.5)*w,(.51-v)*h,.002));p.project(this.camera);q.project(this.camera);up.project(this.camera);let x=(p.x*.5+.5)*this.W,y=(-p.y*.5+.5)*this.H;return[x,y,Math.hypot((q.x-p.x)*this.W/2,(q.y-p.y)*this.H/2),Math.atan2(-(up.y-p.y)*this.H,(up.x-p.x)*this.W)+Math.PI/2];}
 drawBrand(ctx,logos){if(!this.viewState)return;let {i,j,w}=this.viewState;for(const[type,list]of [['pin',[[.5703,.1607,35/1536],[.5573,.1763,32/1536],null,null]],['brooch',[[.5026,.24665,22/1536],[.473,.24665,16/1536],null,null]]]){let a=list[i],b=list[j],wa=a?1-w:0,wb=b?w:0,alpha=wa+wb;if(alpha<.02)continue;let uv=[0,1,2].map(k=>((a?.[k]||0)*wa+(b?.[k]||0)*wb)/alpha);let[x,y,size,angle]=this.projectSubject(...uv);ctx.save();ctx.globalAlpha=alpha;vector(ctx,type==='pin'?logos.spark:logos.anthropic,x,y,size,angle,type==='pin'?undefined:'#FAF9F5');ctx.restore();}}
 renderHelix(t,frame,u){let p=helixPath(u);setCamera(this.camera,p.position,p.target,24,p.roll);this.spark.material.opacity=smoothstep(.55,.8,u);if(this.sky){let forward=new V();this.camera.getWorldDirection(forward);this.sky.position.copy(this.camera.position).addScaledVector(forward,80);this.sky.quaternion.copy(this.camera.quaternion);this.sky.rotateZ(-p.roll);this.sky.scale.setScalar(1.18);}this.ribbons.forEach((m,index)=>{let controls=[];for(let j=0;j<=32;j++){let s=j/32,th=s*17+index*Math.PI+t*.2,r=.35+s*9;controls.push(new V(Math.cos(th)*r,Math.sin(th)*r*.5+1.4,Math.sin(th*1.12)*r*.5));}let curve=new THREE.CatmullRomCurve3(controls),uv=m.geometry.attributes.uv,positions=m.geometry.attributes.aCurve,normals=m.geometry.attributes.aNormal;for(let j=0;j<uv.count;j++){let s=uv.getX(j),p=curve.getPoint(s),tan=curve.getTangent(s),normal=new V(-tan.y,tan.x,.12).normalize();positions.setXYZ(j,p.x,p.y,p.z);normals.setXYZ(j,normal.x,normal.y,normal.z);}positions.needsUpdate=normals.needsUpdate=true;m.material.uniforms.uTime.value=t;m.material.uniforms.uProgress.value=smoothstep(.05,.8,u);});let hp=smoothstep(.1,.3,u);this.halo.position.copy(new V(0,2.3,0).lerp(this.haloGate,hp));this.halo.quaternion.copy(this.haloStart).slerp(this.haloGateRotation,hp);this.halo.quaternion.multiply(new THREE.Quaternion().setFromAxisAngle(new V(0,0,1),t*.2));this.halo.material.opacity=1-smoothstep(.38,.58,u);this.lyric.quaternion.copy(this.camera.quaternion);this.lyric.material.opacity=smoothstep(0,3/106,u);let textEase=smoothstep(.08,.4,u),forward=new V();this.camera.getWorldDirection(forward);let nearText=this.camera.position.clone().addScaledVector(forward,5).add(new V(0,-.55,0));this.lyric.position.copy(nearText.lerp(new V(-3,1.6,0),textEase));this.lyric.scale.setScalar(lerp(.35,1,textEase));this.particles.material.uniforms.uTime.value=t;for(let m of this.subjects)m.lookAt(this.camera.position);this.updateViews(t,p.theta);this.post.uniforms.uTime.value=t;this.post.uniforms.uFrame.value=frame;this.post.uniforms.uFlash.value=u<.025?1:0;this.composer.render(0);if(this.renderer.getContext().getError()!==0)throw Error('WebGL error in hero render');return this.canvas;}
 async compile(){await this.renderer.compileAsync(this.scene,this.camera);}
}
