export const FONT_FILES=[['NotoSerifSC-Black','NotoSerifSC-Black.otf'],['NotoSerifSC-SemiBold','NotoSerifSC-SemiBold.otf'],['NotoSansSC-Bold','NotoSansSC-Bold.otf'],['Lora-SemiBold','Lora-SemiBold.ttf'],['Poppins','Poppins-Regular.ttf'],['Symbols','NotoSansSymbols2-Regular.ttf'],['Math','NotoSansMath-Regular.ttf']];
const {clamp,hash01,smoothstep}=window.RT;
export async function loadFonts(){for(const[n,f]of FONT_FILES){const ff=new FontFace(n,`url(/fonts/${f})`);await ff.load();document.fonts.add(ff);if(!document.fonts.check(`40px "${n}"`))throw Error('Font missing: '+n);}}
export const family=(n)=>`"${n}","Symbols","Math"`;
export function write(ctx,text,x,y,size=42,color='#FAF9F5',font='NotoSerifSC-SemiBold',align='center',outline=0){ctx.font=`${size}px ${family(font)}`;ctx.textAlign=align;ctx.textBaseline='alphabetic';ctx.lineJoin='round';if(outline){ctx.lineWidth=outline;ctx.strokeStyle='#141413';ctx.strokeText(text,x,y);}ctx.fillStyle=color;ctx.fillText(text,x,y);}
export function lyric(ctx,film,t,W,H){let i=film.lyrics.findLastIndex(v=>t>=v.frame/30);if(i<0)return;let l=film.lyrics[i],end=(film.lyrics[i+1]?.frame??1311)/30;if(t>=30.68&&t<34.21)return;let alpha=Math.min(clamp((t-l.frame/30)*10,0,1),clamp((end-t)*10,0,1));ctx.save();ctx.globalAlpha=alpha;ctx.shadowColor='#141413';ctx.shadowBlur=6*H/1080;ctx.shadowOffsetY=2*H/1080;const sz=H*.047;ctx.font=`${sz}px ${family('NotoSerifSC-SemiBold')}`;const parts=l.text.split(/(明天|今天|存在|呼吸|脚踝|你|飞|爱|灿烂)/g);let x=(W-ctx.measureText(l.text).width)/2;for(const p of parts){write(ctx,p,x,H*(t<11.92?.82:.89),sz,/^(明天|今天|存在|呼吸|脚踝|你|飞|爱|灿烂)$/.test(p)?'#D97757':'#FAF9F5','NotoSerifSC-SemiBold','left',1.5*H/1080);x+=ctx.measureText(p).width;}ctx.restore();}
export function layoutDanmaku(ctx,items,W,H){let lanes=Array(16).fill(null);let wallRights=Array(15).fill(W*.16);return items.map((d,i)=>{let size=H*(d.large?.08:.036);ctx.font=`${size}px ${family('NotoSansSC-Bold')}`;let w=ctx.measureText(d.text).width;let speed=d.speed*H/1080;if(d.t0>=37&&d.t0<39.9){let lane=wallRights.indexOf(Math.min(...wallRights));let wallIndex=items.filter(v=>v.t0>=37&&v.t0<39.9).indexOf(d);let startX=wallRights[lane];wallRights[lane]+=w+W*.075;let on=38.8+wallIndex*.012;speed=(220+lane*11)*H/1080;return{...d,t0:on-(W-startX)/speed,on,end:39.9,size,w,speed,lane,y:H*.08+lane*H*.051};}let lane=lanes.findIndex(p=>!p||(W-(d.t0-p.t0)*p.speed+p.w<W-24*H/1080 && (speed<=p.speed || (W+p.w)/(p.speed)-(d.t0-p.t0)<(W-w)/(speed))));if(lane<0){lane=i%lanes.length;d={...d,t0:Math.max(d.t0,lanes[lane].t0+(lanes[lane].w+30*H/1080)/lanes[lane].speed)};}const item={...d,size,w,speed,lane,y:H*.1+lane*H*.041};lanes[lane]=item;return item;});}
export function danmaku(ctx,items,t,W,H){ctx.save();ctx.globalAlpha=.85;for(const d of items){if(t<(d.on??d.t0)||t>d.end)continue;let x=W-(t-d.t0)*d.speed;if(x<-d.w)continue;if(d.large)x=W*.5-d.w*.5;write(ctx,d.text,x,d.large?H*.2:d.y,d.size,d.color,'NotoSansSC-Bold','left',3*H/1080);}ctx.restore();}
export function rounded(ctx,x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
