/** Browser film compositor. Every frame is random-access and deterministic.
 * Asset URLs resolve at the project URL root. Missing required production inputs throw.
 * renderFrame is async; loading/validation occurs only for the selected shot.
 */
import {createRigCamera} from './camera/rig.mjs';
import {createParallax} from './parallax.mjs';
import {createEffect,seededRandom} from './effects.mjs';
import {createTitleSlam} from './title3d.mjs';
import {createGraphics} from './graphics.mjs';
import {installShotDetails} from './shot_details.mjs';
const C={clay:'#D97757',ivory:'#FAF9F5',paper:'#F0EEE6',slate:'#191919',sky:'#6A9BCB',olive:'#788C5D',fig:'#C46686'};
const clamp=x=>Math.max(0,Math.min(1,x));
const smooth=x=>{x=clamp(x);return x*x*(3-2*x);};
const PURE=new Set(['S06','S08b','S09b','S10','S29','S38','S39']);
const IMPACT=new Set([359,686,1014,1095,1177]);
const makeCanvas=(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c;};
export async function createFilm({THREE:T,SVGLoader,width=1920,height=1080,assetMap={},shots,sync,onsets={},cameraPaths,brand={},fonts={}}){
 if(!T||!SVGLoader||!shots?.length||!sync)throw new Error('Film requires THREE, SVGLoader, shots and sync');
 const fps=sync.fps||30,totalFrames=sync.frames||1311,aspect=width/height,worldH=20*Math.tan(25*Math.PI/180),worldW=worldH*aspect;
 const canvas=makeCanvas(width,height),comp=makeCanvas(width,height),maskCanvas=makeCanvas(width,height),glowCanvas=makeCanvas(width,height),ctx=comp.getContext('2d'),out=canvas.getContext('2d'),maskCtx=maskCanvas.getContext('2d');
 const renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setSize(width,height);renderer.setPixelRatio(1);renderer.outputColorSpace=T.SRGBColorSpace;renderer.setClearColor(C.paper,1);
 const postRenderer=new T.WebGLRenderer({antialias:false,alpha:false,preserveDrawingBuffer:true});postRenderer.setSize(width,height);postRenderer.outputColorSpace=T.SRGBColorSpace;
 const resources=[],images=new Map(),textures=new Map(),states=new Map(),diagnostics={shots:{},warnings:[],missing:[],renderedFrames:[],cameraOwner:'code',renderMethod:'depth-mesh / separated-layer / authored-code',finalApproval:false};
 let disposed=false;
 const own=x=>(resources.push(x),x),url=p=>p.startsWith('/')||/^[a-z][a-z0-9+.-]*:/i.test(p)?p:typeof assetMap.resolveURL==='function'?assetMap.resolveURL(p):'/'+p;
 const fail=(id,key)=>{const message=`${id}: required asset ${key} missing`;diagnostics.missing.push(message);throw new Error(message);};
 const image=async(p,id='global',key='image')=>{if(!p)fail(id,key);if(typeof p!=='string')return p;if(!images.has(p))images.set(p,new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error(`${id}: unable to load ${key}: ${p}`));im.src=url(p);}));return images.get(p);};
 const raw=async(p)=>{const r=await fetch(url(p));if(!r.ok)throw new Error(`Required source ${p}: HTTP ${r.status}`);return r.text();};
 const texture=async(p,id,key)=>{if(p?.isTexture)return p;if(textures.has(p))return textures.get(p);const im=await image(p,id,key),tx=own(new T.Texture(im));tx.colorSpace=T.SRGBColorSpace;tx.needsUpdate=true;textures.set(p,tx);return tx;};
 // Load local production fonts before rasterizing any exact glyphs.
 const fontFiles={'Noto Serif SC':'NotoSerifSC.ttf','Noto Sans SC':'NotoSansSC.ttf','LXGW WenKai':'LXGWWenKai.ttf','Newsreader':'Newsreader.ttf','Inter':'Inter.ttf','JetBrains Mono':'JetBrainsMono.ttf'};
 await Promise.all(Object.entries(fontFiles).map(async([name,file])=>{const face=new FontFace(name,`url(${url(assetMap.fonts?.[name]||'assets/fonts/'+file)})`,{weight:name==='LXGW WenKai'?'400':'100 900'});await face.load();document.fonts.add(face);}));await document.fonts.ready;
 if(!brand.svg)brand.svg=await raw(assetMap.sparkSVG||'assets/brand/spark.svg');if(!brand.image)brand.image=await image('data:image/svg+xml;charset=utf-8,'+encodeURIComponent(brand.svg),'global','sparkSVG');
 const graphics=createGraphics({width,height,sync,shots,onsets,fonts,brand});
 const atlas=makeCanvas(1024,1024),ac=atlas.getContext('2d');ac.fillStyle=C.ivory;ac.font='500 82px "Noto Sans SC"';ac.textAlign='center';ac.textBaseline='middle';const glyphs=Array.from('第一天我存在呼吸畅快未来展开真实感因为你飞起来爱腾空魔幻纯真色彩永远灿烂学习思考作品今天明天自在{}[]01');for(let i=0;i<64;i++)ac.fillText(glyphs[i%glyphs.length],i%8*128+64,Math.floor(i/8)*128+64);const glyphAtlas=own(new T.CanvasTexture(atlas));glyphAtlas.colorSpace=T.SRGBColorSpace;
 const postTexture=own(new T.CanvasTexture(comp));postTexture.colorSpace=T.SRGBColorSpace;const glowTexture=own(new T.CanvasTexture(glowCanvas));glowTexture.colorSpace=T.SRGBColorSpace;
 const postScene=new T.Scene(),postCamera=new T.Camera(),postUniforms={glow:{value:glowTexture},source:{value:postTexture},resolution:{value:new T.Vector2(width,height)},frame:{value:0},chorus:{value:0},impact:{value:0},pulse:{value:0},freeze:{value:0},shock:{value:0},shockActive:{value:0}};
 const postMat=own(new T.ShaderMaterial({uniforms:postUniforms,depthTest:false,depthWrite:false,vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}',fragmentShader:`varying vec2 vUv;uniform sampler2D source,glow;uniform vec2 resolution;uniform float frame,chorus,impact,pulse,freeze,shock,shockActive;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}void main(){vec2 uv=vUv;vec2 radial=(uv-.5)*vec2(resolution.x/resolution.y,1.);float radius=length(radial);float shockBand=exp(-pow((radius-shock*1.15)/.035,2.))*shockActive*(1.-shock);uv+=normalize(radial+vec2(.00001))*.017*shockBand;vec2 delta=(uv-.5)*(1.5*impact+.25*pulse)/resolution;vec3 c=vec3(texture2D(source,uv+delta).r,texture2D(source,uv).g,texture2D(source,uv-delta).b);vec3 bloom=vec3(0.);for(int by=-1;by<=1;by++){for(int bx=-1;bx<=1;bx++){vec3 tap=texture2D(glow,uv+vec2(float(bx),float(by))*3./resolution).rgb;bloom+=tap*smoothstep(.8,1.,max(tap.r,max(tap.g,tap.b)));}}c+=bloom/9.*.6;float l=dot(c,vec3(.2126,.7152,.0722));c=mix(vec3(l),c,mix(.6,1.15,chorus));c*=vec3(1.025,1.008,.985);c=mix(vec3(.0091,.0086,.007),c,.986);c=clamp(c,0.,.957);float vignette=1.-.15*smoothstep(.2,.78,length(uv-.5));c*=vignette;float dots=step(.64,length(fract(gl_FragCoord.xy/6.)-.5));c*=1.-dots*.065*chorus*(1.-smoothstep(.05,.30,l));float grain=(hash(gl_FragCoord.xy+vec2(frame*31.,frame*17.))-.5)*.05;c+=grain*(.24+.35*sqrt(max(l,0.)));c*=1.+pulse*.025;if(impact>1.5){c=l>.42?vec3(.956,.947,.913):vec3(.694,.184,.095);}gl_FragColor=vec4(c,1.);\n#include <colorspace_fragment>\n}` }));postScene.add(new T.Mesh(own(new T.PlaneGeometry(2,2)),postMat));
 function labelCanvas(text,{w=1024,h=256,size=100,family='Noto Serif SC',color=C.slate,background=C.ivory}={}){const c=makeCanvas(w,h),g=c.getContext('2d');if(background){g.fillStyle=background;g.fillRect(0,0,w,h);}g.fillStyle=color;g.textAlign='center';g.textBaseline='middle';g.font=`900 ${size}px "${family}"`;g.fillText(text,w/2,h/2);return c;}
 function localPlane(state,source,w,h,x=0,y=0,z=.05){const tx=state.own(new T.CanvasTexture(source));tx.colorSpace=T.SRGBColorSpace;const geo=state.own(new T.PlaneGeometry(w,h)),mat=state.own(new T.MeshBasicMaterial({map:tx,transparent:true,side:T.DoubleSide,depthWrite:false}));const mesh=new T.Mesh(geo,mat);mesh.position.set(x,y,z);state.scene.add(mesh);return {mesh,texture:tx,source};}
 function sparkMesh(state,size=2,depth=.08,color=C.clay){const group=new T.Group();for(const p of new SVGLoader().parse(brand.svg).paths)for(const shape of SVGLoader.createShapes(p)){const g=state.own(new T.ExtrudeGeometry(shape,{depth:depth*50,bevelEnabled:false,curveSegments:12}));const m=state.own(new T.MeshBasicMaterial({color}));const mesh=new T.Mesh(g,m);mesh.position.set(-50,-50,0);group.add(mesh);}group.scale.set(size/100,-size/100,size/100);state.scene.add(group);return group;}
 function glyphInstances(state,count,radius=4,turns=.75){const geo=state.own(new T.PlaneGeometry(.16,.16)),indexes=Float32Array.from({length:count},(_,i)=>i%64);geo.setAttribute('tile',new T.InstancedBufferAttribute(indexes,1));const material=state.own(new T.ShaderMaterial({transparent:true,side:T.DoubleSide,depthWrite:false,uniforms:{map:{value:glyphAtlas}},vertexShader:'attribute float tile;varying vec2 vUv;void main(){vUv=(vec2(mod(tile,8.),7.-floor(tile/8.))+uv)/8.;gl_Position=projectionMatrix*modelViewMatrix*instanceMatrix*vec4(position,1.);}',fragmentShader:'uniform sampler2D map;varying vec2 vUv;void main(){gl_FragColor=texture2D(map,vUv)*vec4(1.,.72,.58,1.);\n#include <colorspace_fragment>\n}'}));const mesh=new T.InstancedMesh(geo,material,count);mesh.frustumCulled=false;state.scene.add(mesh);const rnd=seededRandom(55027),points=Array.from({length:count},()=>{const z=rnd()*2-1,a=rnd()*Math.PI*2,r=radius*(.85+rnd()*.15);return new T.Vector3(Math.sqrt(1-z*z)*Math.cos(a)*r,z*r,Math.sqrt(1-z*z)*Math.sin(a)*r);}),dummy=new T.Object3D();return p=>{points.forEach((v,i)=>{dummy.position.copy(v).applyAxisAngle(new T.Vector3(0,1,0),p*Math.PI*2*turns);dummy.quaternion.copy(state.camera.quaternion);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);});mesh.instanceMatrix.needsUpdate=true;};}
 async function build(shot){
  const id=shot.id,a=assetMap.shots?.[id]||{},scene=new T.Scene(),camera=new T.PerspectiveCamera(50,aspect,.01,1000);camera.position.z=10;
  const state={id,shot,a,scene,camera,owned:[],updates:[],afterCamera:[],disposeFns:[],effects:[],maskMesh:null,parallax:null,own(x){this.owned.push(x);return x;}};
  try {
  diagnostics.shots[id]={assets:a,method:PURE.has(id)?'authored-code':'depth-rig',cameraClamps:[],features:Object.keys(a.features||{}),unverified:[]};
  const path=(cameraPaths?.paths||cameraPaths)?.[id];if(!path)throw new Error(`${id}: camera path missing`);state.rig=createRigCamera({THREE:T,camera,path:{...path,cameraOwner:'code'},width,height});state.rig.update(0,shot.f1-shot.f0);
  if(!PURE.has(id)){
   if(id==='S25'&&a.layers?.length!==5)fail(id,'layers (exactly five separated RGBA sources with z)');
   if(!a.layers?.length&&!a.depth)fail(id,'depth');
   const plate=await image(id==='S11'&&a.support?.subject?.path?a.support.subject.path:a.plate,id,'plate'),depth=a.depth?await image(a.depth,id,'depth'):null;state.depthImage=depth;
   const layers=a.layers?.length?await Promise.all(a.layers.map(async l=>({...l,image:await image(l.path,id,`layer:${l.id}`),depth:null,mask:null,rgba:true,opaque:/sky$/i.test(l.id),coverage:/sky$/i.test(l.id)?'background':undefined}))):null;
   state.parallax=createParallax({THREE:T,scene,plate:{image:plate,cropReserve:path.sourceCropReserve,paddingFraction:.10,depthScale:a.depthScale??.65,layerMode:id==='S25'?'infinite-sky':undefined},depth,layers,width,height});state.parallax.setReferenceCamera(camera);state.disposeFns.push(()=>state.parallax.dispose());
   const characterLayer=id==='S25'?a.layers.find(l=>/character/i.test(l.id)):null;state.anchorGroup=characterLayer?state.parallax.layerSourceGroup(characterLayer.id):state.parallax.group;state.anchorZ=characterLayer?.z||0;state.characterLayer=characterLayer;
   if(a.mask||characterLayer){const mask=await image(a.mask||characterLayer.path,id,'mask');const mt=state.own(new T.Texture(mask));mt.colorSpace=T.NoColorSpace;mt.needsUpdate=true;const mm=state.own(new T.ShaderMaterial({transparent:true,side:T.DoubleSide,depthWrite:false,uniforms:{mask:{value:mt},alphaOnly:{value:characterLayer&&!a.mask?1:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 vUv;uniform sampler2D mask;uniform float alphaOnly;void main(){if(vUv.x<0.||vUv.x>1.||vUv.y<0.||vUv.y>1.)discard;vec4 m=texture2D(mask,vUv);gl_FragColor=vec4(1.,1.,1.,mix(m.r*m.a,m.a,alphaOnly));}'}));state.maskMesh=new T.Mesh(characterLayer?state.parallax.meshes.find(m=>m.name===characterLayer.id).geometry:state.parallax.geometry,mm);state.maskTransform=state.anchorGroup;state.maskScene=new T.Scene();state.maskScene.add(state.maskMesh);if(['S11','S13','S20','S27','S33','S36e','S36f','S36h'].includes(id)||a.features?.halo){const sourceMesh=characterLayer?state.parallax.meshes.find(m=>m.name===characterLayer.id):state.parallax.meshes[0];const fm=state.own(new T.MeshBasicMaterial({map:sourceMesh.material.map,alphaMap:characterLayer?null:mt,transparent:true,depthWrite:false,depthTest:false,side:T.DoubleSide}));const fg=new T.Mesh(sourceMesh.geometry,fm);fg.renderOrder=50;state.anchorGroup.add(fg);}}
   if(depth){const dc=makeCanvas(depth.width,depth.height);dc.getContext('2d').drawImage(depth,0,0);state.depthPixels=dc.getContext('2d').getImageData(0,0,dc.width,dc.height);}
   const features=characterLayer?.features||a.features||{};
   function zAt(u,v){if(!state.depthPixels)return state.anchorZ+.02;const d=state.depthPixels,x=Math.max(0,Math.min(d.width-1,Math.round(u*(d.width-1)))),y=Math.max(0,Math.min(d.height-1,Math.round(v*(d.height-1))));return (d.data[(y*d.width+x)*4]/255-.5)*(a.depthScale??.65)+.018;}
   state.zAt=zAt;
   state.sourceAnchor=(u,v,z=zAt(u,v))=>characterLayer?new T.Vector3((u-.5)*worldW,(.5-v)*worldH,z):state.parallax.sourceLocalPoint(u,1-v,z);
   state.sourceScale=z=>characterLayer?1:state.parallax.sourceScaleAtDepth(z);
   const ornaments=[];const reflected=features.reflection||{},ornamentAnchors=[...(features.eyes||[]).map(anchor=>({anchor,color:C.ivory,opacity:1})),...[...(features.hairpin?[features.hairpin]:[]),...(features.tie?[features.tie]:[])].map(anchor=>({anchor,color:C.clay,opacity:1})),...(reflected.eyes||[]).map(anchor=>({anchor,color:C.ivory,opacity:.65})),...[...(reflected.hairpin?[reflected.hairpin]:[]),...(reflected.tie?[reflected.tie]:[])].map(anchor=>({anchor,color:C.clay,opacity:.65}))];for(const {anchor,color,opacity} of ornamentAnchors){const [u,v,size]=anchor,s=sparkMesh(state,Math.max(.008,size*worldW),.008,color);s.position.copy(state.sourceAnchor(u,v));s.scale.multiplyScalar(state.sourceScale(zAt(u,v)));s.traverse(o=>{if(o.isMesh){o.renderOrder=60;o.material.depthTest=false;o.material.transparent=true;o.material.opacity=opacity;o.material.needsUpdate=true;o.userData.bloom=true;}});state.anchorGroup.add(s);ornaments.push(s);}
   state.ornaments=ornaments;
   if(features.halo){const [u,v,w,h]=features.halo,geo=state.own(new T.TorusGeometry(w*worldW/2,.015,8,96)),mat=state.own(new T.MeshBasicMaterial({color:C.clay})),ring=new T.Mesh(geo,mat);ring.material.transparent=true;ring.material.needsUpdate=true;ring.renderOrder=30;ring.scale.y=h*worldH/(w*worldW);ring.position.copy(state.sourceAnchor(u,v));ring.scale.multiplyScalar(state.sourceScale(zAt(u,v)));state.anchorGroup.add(ring);}
   if(reflected.halo){const [u,v,w,h]=reflected.halo,geo=state.own(new T.TorusGeometry(w*worldW/2,.015,8,96)),mat=state.own(new T.MeshBasicMaterial({color:C.clay,transparent:true,opacity:.65})),ring=new T.Mesh(geo,mat);ring.renderOrder=30;ring.scale.y=h*worldH/(w*worldW);ring.position.copy(state.sourceAnchor(u,v));ring.scale.multiplyScalar(state.sourceScale(zAt(u,v)));state.anchorGroup.add(ring);}if(features.reflection)diagnostics.shots[id].reflectionOrnaments={source:'observed source-pixel anchors; no mirrored coordinate inference',opacity:.65,eyes:reflected.eyes?.length||0,hairpin:!!reflected.hairpin,tie:!!reflected.tie,halo:!!reflected.halo};
   if(a.poses?.length){const poses=await Promise.all(a.poses.map(async p=>({...p,image:await image(p.path,id,'pose')})));const pose=localPlane(state,poses[0].image,worldW,worldH,0,0,.40);state.parallax.group.add(pose.mesh);state.updates.push(f=>{let select=poses[0];for(const p of poses)if(f>=p.frame)select=p;if(pose.texture.image!==select.image){pose.texture.image=select.image;pose.texture.needsUpdate=true;}});diagnostics.shots[id].unverified.push('Replacement poses require a clean background plate to avoid duplicate bodies.');}
  }
  if(id==='S11'&&a.support?.background?.path&&a.support?.subject?.path){const subjectGroup=new T.Group();const originalChildren=[...state.parallax.group.children];state.parallax.group.add(subjectGroup);for(const child of originalChildren)subjectGroup.add(child);subjectGroup.scale.setScalar(.19);subjectGroup.position.y=-worldH*.067;subjectGroup.traverse(o=>{if(o.isMesh&&o.material.map){o.material.onBeforeCompile=shader=>{shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>','if(vMapUv.x<0.0||vMapUv.x>1.0||vMapUv.y<0.0||vMapUv.y>1.0) discard;\n#include <map_fragment>');};o.material.customProgramCacheKey=()=> 'S11-cutout-source-uv-clip';o.material.needsUpdate=true;}});state.afterCamera.push(()=>{subjectGroup.position.y=-worldH*.067;const bottom=state.sourceAnchor(.5,1,state.zAt(.5,1)-.018),project=()=>{state.parallax.group.updateMatrixWorld(true);return bottom.clone().applyMatrix4(subjectGroup.matrixWorld).project(camera).y;},current=project();subjectGroup.position.y+=.01;const derivative=(project()-current)/.01;subjectGroup.position.y-=.01;if(Math.abs(derivative)>1e-6)subjectGroup.position.y+=(-1.045-current)/derivative;state.parallax.group.updateMatrixWorld(true);diagnostics.shots[id].subjectBottomNDC=project();});state.maskTransform=subjectGroup;const background=localPlane(state,await image(a.support.background.path,id,'clean background'),worldW*1.8,worldH*1.8,0,0,-1.2);background.mesh.renderOrder=-20;state.parallax.group.add(background.mesh);diagnostics.shots[id].subjectLayout={scale:.19,offsetYSourceFraction:.067,background:a.support.background.path,subject:a.support.subject.path,requiresMatchingOriginalDepthAndAnchors:true};}else if(id==='S11'){diagnostics.shots[id].unverified.push('Readable header composition requires support.background.path and support.subject.path matching original source coordinates; current full-frame body may occlude title.');}
  const addFx=(name,assets={})=>{const effect=createEffect(name,{THREE:T,scene,camera,renderer,assets:{glyphAtlas,...assets},width,height});if(['TokenTunnel','GlassCrack','Mosaic'].includes(name))effect.root.children.forEach((o,i)=>{if(o.isMesh&&(name!=='GlassCrack'||i===0))o.userData.bloom=true;});state.effects.push(effect);state.disposeFns.push(()=>effect.dispose());return effect;};
  if(id==='S06')addFx('TokenTunnel');
  if(id==='S08b'){
   const box=state.own(new T.BoxGeometry(1.65,4,1.1)),mat=state.own(new T.MeshStandardMaterial({color:'#313B42',roughness:.9}));const light=new T.PointLight(C.clay,95,35);light.position.set(0,2,4);scene.add(light,new T.AmbientLight(C.ivory,1.8));const strips=[];
   for(let row=0;row<14;row++)for(const side of [-1,1]){const rack=new T.Mesh(box,mat);rack.position.set(side*3.2,0,-row*2.2);scene.add(rack);for(let slot=0;slot<6;slot++){const m=state.own(new T.MeshBasicMaterial({color:C.clay,transparent:true,opacity:.15})),strip=new T.Mesh(state.own(new T.PlaneGeometry(1.35,.07)),m);strip.position.set(side*3.2,slot*.5-1.25,-row*2.2+.57);strip.userData.bloom=true;scene.add(strip);strips.push({strip,row,slot});const inner=new T.Mesh(state.own(new T.PlaneGeometry(.9,.13)),m);inner.position.set(side*2.365,slot*.5-1.25,-row*2.2);inner.rotation.y=-side*Math.PI/2;inner.userData.bloom=true;scene.add(inner);}}
   state.updates.push((f,p)=>strips.forEach(({strip,row,slot})=>{const wave=Math.exp(-Math.pow((row-p*17+1)/2.8,2));strip.material.opacity=.32+.68*wave;strip.material.color.set(C.clay).multiplyScalar(.8+wave*1.5);strip.scale.y=1+wave*.7;}));
  }
  if(id==='S09b'||id==='S10'){const s=sparkMesh(state,id==='S10'?2.6:3.1,.10,id==='S10'?C.slate:C.clay);state.updates.push((f,p)=>{if(id==='S10'){s.scale.set(2.6/100,-2.6/100,2.6/100);s.position.y=1.21;s.rotation.z=0;}else{s.scale.setScalar(3.1/100*(.1*Math.pow(60,p)));s.scale.y*=-1;s.rotation.z=p*Math.PI/2;}});}
  if(id==='S11'){if(!assetMap.shell)fail(id,'assetMap.shell (shell-only RGBA)');addFx('Shatter',{egg:await texture(assetMap.shell,id,'shell')});const left=await raw('assets/brand/title-left.svg'),right=await raw('assets/brand/title-right.svg');const title=createTitleSlam({THREE:T,scene,SVGLoader,svgPaths:{left,right},sparkSVG:brand.svg,camera,fitCamera:false,position:[0,1.6,.5]});state.afterCamera.push((f,p)=>{title.update(f,shot.f1-shot.f0);const distance=6,viewH=2*distance*Math.tan(camera.fov*Math.PI/360),scale=(180/1080*viewH)/title.metadata.capHeight;title.root.scale.setScalar(scale);title.root.quaternion.copy(camera.quaternion);title.root.position.set(0,(.5-220/1080)*viewH,-distance).applyQuaternion(camera.quaternion).add(camera.position);title.root.updateMatrixWorld(true);if(f>=5){const box=new T.Box3().setFromObject(title.root.children[0]),limits={left:Infinity,right:-Infinity,top:Infinity,bottom:-Infinity};for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z]){const v=new T.Vector3(x,y,z).project(camera),px=(v.x*.5+.5)*1920,py=(.5-v.y*.5)*1080;limits.left=Math.min(limits.left,px);limits.right=Math.max(limits.right,px);limits.top=Math.min(limits.top,py);limits.bottom=Math.max(limits.bottom,py);}diagnostics.shots[id].titleProjectedBounds=limits;}});state.disposeFns.push(()=>title.dispose());diagnostics.shots[id].unverified.push('Title/foreground subject depth intersection requires visual review.');}
  if(id==='S19'||id==='S20'){const source=graphics.texture('ChatWindow',{frame:shot.f0});let panel;if(id==='S19'){const quad=a.features?.screenQuad;if(!Array.isArray(quad)||quad.length!==4)fail(id,'features.screenQuad [TL,TR,BR,BL] inner display corners');const positions=quad.flatMap(([u,v])=>state.sourceAnchor(u,v,state.zAt(u,v)+.006).toArray());const geo=state.own(new T.BufferGeometry());geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));geo.setAttribute('uv',new T.Float32BufferAttribute([0,1,1,1,1,0,0,0],2));geo.setIndex([0,3,1,1,3,2]);geo.computeVertexNormals();const tx=state.own(new T.CanvasTexture(source));tx.colorSpace=T.SRGBColorSpace;const material=state.own(new T.MeshBasicMaterial({map:tx,transparent:true,side:T.DoubleSide,depthWrite:false,depthTest:false}));const mesh=new T.Mesh(geo,material);mesh.renderOrder=20;state.parallax.group.add(mesh);panel={mesh,texture:tx};diagnostics.shots[id].screenQuad=quad;}else{panel=localPlane(state,source,9,5.35,0,0,.6);panel.mesh.rotation.y=-.12;panel.mesh.renderOrder=20;panel.mesh.material.depthTest=false;}state.updates.push(f=>{graphics.texture('ChatWindow',{frame:shot.f0+f});panel.texture.needsUpdate=true;});if(id==='S20'){const crack=addFx('GlassCrack',{plate:await texture(a.plate,id,'plate')});crack.root.children[0].renderOrder=25;}}
  if(['S09b','S25','S26'].includes(id))addFx('SpeedLines');
  if(id==='S25'){
   if(!state.characterLayer)fail(id,'S25-character separated RGBA layer');const characterGroup=state.parallax.layerSourceGroup(state.characterLayer.id),characterMesh=state.parallax.meshes.find(m=>m.name===state.characterLayer.id);characterGroup.scale.multiplyScalar(.60);const bodyWorldHeight=worldH*characterGroup.scale.y*state.parallax.group.scale.y,sourceCenter=new T.Vector3(0,0,state.characterLayer.z).multiply(characterGroup.scale);
   state.updates.push((f,p)=>{const ahead=state.rig.sample(Math.min(1,(f+6)/Math.max(1,shot.f1-shot.f0-1))),lead=new T.Vector3(...ahead.target).project(camera),screenTarget=new T.Vector3(Math.max(-.2,Math.min(.2,lead.x)),Math.max(-.10,Math.min(.24,lead.y)),.5),ray=screenTarget.unproject(camera).sub(camera.position).normalize();let distance=bodyWorldHeight/(2*Math.tan(camera.fov*Math.PI/360)*.62);state.parallax.group.updateMatrixWorld(true);const inverse=state.parallax.group.matrixWorld.clone().invert();for(let iteration=0;iteration<3;iteration++){const desired=camera.position.clone().addScaledVector(ray,distance);characterGroup.position.copy(desired.applyMatrix4(inverse).sub(sourceCenter));state.parallax.group.updateMatrixWorld(true);const corners=[[0,0],[1,0],[1,1],[0,1]].map(([u,v])=>new T.Vector3((u-.5)*worldW,(v-.5)*worldH,state.characterLayer.z).applyMatrix4(characterGroup.matrixWorld).project(camera));const projectedHeight=(Math.max(...corners.map(v=>v.y))-Math.min(...corners.map(v=>v.y)))/2;distance*=projectedHeight/.62;}diagnostics.shots[id].followFraming={localFrame:f,leadFrames:6,constantWorldBodyHeight:bodyWorldHeight,cameraDistance:distance,targetHeightFraction:.62,groupScale:characterGroup.scale.toArray()};});
   const wallLayers=state.parallax.meshes.filter(m=>m.name!==state.characterLayer.id&&!/sky$/i.test(m.name));state.parallax.group.updateMatrixWorld(true);const initialTops=new Map(wallLayers.map(m=>{const bounds=m.geometry.boundingBox,top=[bounds.min.x,bounds.max.x].map(x=>new T.Vector3(x/(1.2),worldH/2,bounds.min.z).applyMatrix4(m.matrixWorld).project(camera).y);return [m.name,Math.min(...top)];}));state.updates.push((f,p)=>{state.parallax.group.updateMatrixWorld(true);for(const wall of wallLayers){const z=wall.geometry.boundingBox.min.z,top=[-worldW/2,worldW/2].map(x=>new T.Vector3(x,worldH/2,z).applyMatrix4(wall.matrixWorld).project(camera).y),topY=Math.min(...top),initial=initialTops.get(wall.name);wall.material.opacity=smooth((topY-1.005)/Math.max(.01,initial-1.005));}});
   const fontData=JSON.parse(await raw('assets/brand/canyon-hanzi.json')),units=fontData.unitsPerEm;const faces=[C.ivory,C.paper,'#E3DACC'].map(color=>state.own(new T.MeshStandardMaterial({color,roughness:.98}))),sides=state.own(new T.MeshStandardMaterial({color:'#79766E',roughness:.98}));const glyphGeometry=fontData.glyphs.map(glyph=>new SVGLoader().parse(`<svg xmlns="http://www.w3.org/2000/svg"><path d="${glyph.d}"/></svg>`).paths.flatMap(p=>SVGLoader.createShapes(p).map(shape=>state.own(new T.ExtrudeGeometry(shape,{depth:units*.62,bevelEnabled:true,bevelThickness:units*.012,bevelSize:units*.012,bevelSegments:1,curveSegments:6})))));
   const towerRoot=new T.Group();towerRoot.name='CanyonTrueHanziTowers';scene.add(towerRoot);let blocks=0;for(const side of [-1,1])for(let column=0;column<5;column++)for(let level=0;level<14-column;level++){const glyphIndex=(level+column*3+(side===1?1:0))%glyphGeometry.length,block=new T.Group();for(const geometry of glyphGeometry[glyphIndex])block.add(new T.Mesh(geometry,[faces[(level+column)%3],sides]));block.scale.set(1.8/units,-1.8/units,1.8/units);block.position.set(side*(5.9+column*.95),-4+level*2.15,-1-column*3.1);block.rotation.y=side*(.08+column*.025);towerRoot.add(block);blocks++;}scene.add(new T.AmbientLight(C.ivory,1.9));const sun=new T.DirectionalLight('#FAF9F5',1.8);sun.position.set(-4,18,10);scene.add(sun);diagnostics.shots[id].canyon={method:'local Noto Serif SC900 glyph outlines, actual ExtrudeGeometry stacked towers',blocks,glyphs:fontData.glyphs.map(g=>g.char),layerMode:'infinite-sky',characterFollowLeadFrames:6,constantBodyWorldSize:true,positiveCameraRelativeDistance:true,targetBodyHeightFraction:.62,finiteWalls:'opacity fades before top source boundary enters viewport'};
  }
  if(id==='S27'){const anchor=a.features?.heart;if(!anchor)fail(id,'features.heart [u,v] chest anchor');const cloud=glyphInstances(state,1200,4.4,1);state.updates.push((f,p)=>cloud(p));const heartGroup=new T.Group(),heart=sparkMesh(state,.48,.015);heartGroup.add(heart);heart.traverse(o=>{if(o.isMesh){o.material.transparent=true;o.material.depthTest=false;o.material.needsUpdate=true;o.renderOrder=65;o.userData.bloom=true;}});const outline=Array.from({length:96},(_,i)=>{const t=i/96*Math.PI*2;return new T.Vector3(16*Math.sin(t)**3/18*.40,(13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t))/18*.40,-.015);});const heartLine=new T.LineLoop(state.own(new T.BufferGeometry().setFromPoints(outline)),state.own(new T.LineBasicMaterial({color:C.clay,transparent:true,opacity:.38,depthTest:false,depthWrite:false})));heartLine.renderOrder=64;heartGroup.add(heartLine);heartGroup.position.copy(state.sourceAnchor(...anchor,state.zAt(...anchor)+.03));state.anchorGroup.add(heartGroup);state.updates.push((f,p)=>heartGroup.scale.setScalar(1+.07*Math.sin(f*.4)));diagnostics.shots[id].heart={anchor,exactBrandSpark:true,subtleHeartOutline:true};diagnostics.shots[id].particleOrbitDegrees=360;}

  if(id==='S28a'){const halo=a.features?.halo;if(!halo)fail(id,'features.halo for stamp strike');const [hu,hv,hw,hh]=halo,target=[hu+hw/2*Math.cos(Math.PI*35/180),hv+hh/2*Math.sin(Math.PI*35/180)],source=graphics.texture('Stamp',{frame:shot.f0,width:1920,height:1080,x:960,y:475,scale:1,angle:0}),crop=makeCanvas(454,268);crop.getContext('2d').drawImage(source,733,341,454,268,0,0,454,268);const available=Math.max(.08,.91-target[0]),w=Math.min(.18,available),h=w*1920/1080*268/454;const stamp=localPlane(state,crop,w*worldW,h*worldH,0,0,.15);state.anchorGroup.add(stamp.mesh);stamp.mesh.material.depthTest=false;stamp.mesh.renderOrder=25;const at=state.sourceAnchor(target[0]+w/2,target[1]+h*.4,state.zAt(...target)+.12),tx=at.x-w*worldW/2,ty=at.y,z=at.z;state.updates.push((f,p)=>{const bounce=f<=2?(2-f)/2:Math.min(1,(f-2)/6),travel=worldW*.035*bounce;stamp.mesh.position.set(tx+w*worldW/2+travel,ty-Math.sin(p*Math.PI)*.08,z);stamp.mesh.rotation.z=(f<=2?-.30:-.12+.22*smooth((f-2)/6));stamp.mesh.scale.setScalar(f===2?.92:1);});diagnostics.shots[id].stampStrike={haloRight:target,contactLocalFrame:2,widthSourceFraction:w,geometry:'cropped exact seal on physical source-registered plane'};}

  if(id==='S28b'){const punch=a.features?.punch;if(!punch)fail(id,'features.punch for toast strike');const c=graphics.texture('Toast',{frame:shot.f0,width:1920,height:1080,x:545,y:390}),crop=makeCanvas(842,162);crop.getContext('2d').drawImage(c,539,384,842,162,0,0,842,162);const toast=state.own(new T.CanvasTexture(crop));toast.colorSpace=T.SRGBColorSpace;let safeLeft=0,unsafeLeft=punch[0];const projectLeft=u=>{const q=state.sourceAnchor(u,punch[1],state.zAt(...punch)+.12).applyMatrix4(state.anchorGroup.matrixWorld).project(camera);return (q.x+1)/2;};state.parallax.group.updateMatrixWorld(true);for(let i=0;i<28;i++){const mid=(safeLeft+unsafeLeft)/2;if(projectLeft(mid)<.075)safeLeft=mid;else unsafeLeft=mid;}const w=Math.min(.42,punch[0]-unsafeLeft);if(w<.12)throw new Error('S28b punch anchor leaves insufficient safe width to its left for exact toast typography');const h=w*1920/1080*162/842,center=[punch[0]-w/2,punch[1]],fx=addFx('ToastShatter',{toast});state.anchorGroup.add(fx.root);fx.root.position.copy(state.sourceAnchor(...center,state.zAt(...punch)+.12));fx.root.scale.set(w*worldW/(6*aspect),h*worldH/6,.18);const inf=localPlane(state,labelCanvas('∞',{w:512,h:512,size:280,family:'Newsreader',color:C.clay,background:null}),h*worldH*1.7,h*worldH*1.7,(center[0]-.5)*worldW,(.5-center[1])*worldH,state.zAt(...punch)+.15);inf.mesh.position.copy(state.sourceAnchor(...center,state.zAt(...punch)+.15));state.anchorGroup.add(inf.mesh);inf.mesh.material.depthTest=false;inf.mesh.renderOrder=25;state.updates.push((f,p)=>{inf.mesh.visible=f>=3;fx.root.visible=f<8;for(const shard of fx.root.children)if(shard.isMesh){shard.position.x=Math.min(shard.position.x,3*aspect*.85);shard.material.depthTest=false;shard.renderOrder=24;}});diagnostics.shots[id].toastStrike={punch,rightEdge:punch[0],leftEdge:punch[0]-w,widthSourceFraction:w,estimatedTextSizePx:42*w*1920/842,fractureStartLocalFrame:1,completeToastLocalFrame:0};}

  if(id==='S28c'){if(!a.cloudFree&&!/S28c-clean/i.test(a.plate||''))fail(id,'cloud-free S28c-clean source (or explicit cloudFree:true after review)');const eyeAnchors=a.features?.eyes||[],halo=a.features?.halo,center=a.features?.cloud||[halo?.[0]??(eyeAnchors.length?eyeAnchors.reduce((x,e)=>x+e[0],0)/eyeAnchors.length:.5),Math.max(.13,(eyeAnchors.length?Math.min(...eyeAnchors.map(e=>e[1])):.4)-.2)],w=.24,h=w*1920/1080*240/470,source=graphics.texture('LabelCloud',{frame:shot.f0,width:1920,height:1080,x:960,y:205}),crop=makeCanvas(470,240);crop.getContext('2d').drawImage(source,725,65,470,240,0,0,470,240);const cloud=localPlane(state,crop,w*worldW,h*worldH,(center[0]-.5)*worldW,(.5-center[1])*worldH,.4);state.anchorGroup.add(cloud.mesh);cloud.mesh.material.depthTest=false;cloud.mesh.renderOrder=25;state.cloudOrigin=state.sourceAnchor(...center,.4);cloud.mesh.position.copy(state.cloudOrigin);state.updates.push((f,p)=>{cloud.mesh.material.opacity=1-smooth(p*2);});diagnostics.shots[id].cloudStaging={center,origin:'source-registered code cloud; confetti shares same origin',requiresCloudFreeSource:true};}

  if(id==='S29')addFx('InkBloom');
  if(id==='S34'){const rnd=seededRandom(5534),blooms=[];for(let i=0;i<80;i++){const x=(rnd()-.5)*worldW,y=(rnd()-.5)*worldH;const bloom=i%3?sparkMesh(state,.15+rnd()*.2,.01):localPlane(state,labelCanvas('{}',{w:256,h:256,size:170,color:i%2?C.olive:C.clay,background:null}),.4,.4).mesh;bloom.position.set(x,y,.4);blooms.push({mesh:bloom,s:bloom.scale.clone(),at:rnd()*.6});}state.updates.push((f,p)=>blooms.forEach(b=>b.mesh.scale.copy(b.s).multiplyScalar(smooth((p-b.at)*4))));}
  if(id==='S37'){const ringGroup=new T.Group(),geometry=state.own(new T.TorusGeometry(1,.006,10,160)),material=state.own(new T.MeshBasicMaterial({color:C.clay,transparent:true,depthWrite:false})),ring=new T.Mesh(geometry,material);ringGroup.add(ring);scene.add(ringGroup);for(let i=0;i<12;i++){const angle=i*Math.PI/6,pl=localPlane(state,labelCanvas('5.5',{w:256,h:128,size:85,family:'Newsreader',color:C.clay,background:null}),.12,.06,Math.sin(angle)*1.035,Math.cos(angle)*1.035,.015);pl.mesh.rotation.z=-angle;ringGroup.add(pl.mesh);}state.afterCamera.push((f,p)=>{const distance=6,viewH=2*distance*Math.tan(camera.fov*Math.PI/360),opacity=smooth((p-.55)/.4)*.8;ringGroup.quaternion.copy(camera.quaternion);ringGroup.scale.setScalar(viewH*.425);ringGroup.position.set(0,-.02*viewH,-distance).applyQuaternion(camera.quaternion).add(camera.position);ringGroup.traverse(o=>{if(o.isMesh)o.material.opacity=opacity;});});}
  if(id==='S38'){if(!assetMap.mosaicAtlas)fail(id,'assetMap.mosaicAtlas extracted from completed S01–S37');if(!assetMap.mosaicHero)fail(id,'assetMap.mosaicHero lossless finished frame1217');if(assetMap.mosaicIsTest&&!assetMap.allowTestMosaic)throw new Error('S38 test mosaic requires explicit assetMap.allowTestMosaic');state.mosaicHeroImage=await image(assetMap.mosaicHero,id,'mosaicHero');if(Math.abs(state.mosaicHeroImage.width/state.mosaicHeroImage.height-aspect)>.001)throw new Error('S38 mosaicHero must have the film aspect ratio');const mosaic=addFx('Mosaic',{mosaicAtlas:await texture(assetMap.mosaicAtlas,id,'mosaicAtlas'),mosaicHero:await texture(assetMap.mosaicHero,id,'mosaicHero'),sparkSVG:brand.svg});state.effectCameraOwner='Mosaic';diagnostics.shots[id].mosaicTest=!!assetMap.mosaicIsTest;diagnostics.shots[id].mosaicProjection=mosaic.metadata.projection;diagnostics.shots[id].cameraOwner='fitted Mosaic projection';diagnostics.shots[id].mosaicBridge={heroNativeResolution:[state.mosaicHeroImage.width,state.mosaicHeroImage.height],outputResolution:[width,height],fromFrame:1217,toFrame:1218,source:assetMap.mosaicHero,firstFrame:'direct lossless source image blit',followingFrames:'same image on fitted central3D tile',globalFinishBypassed:true,actualSeamQA:'pending'};}
  if(id==='S02'){
   // Observed interior hardware corners in the original 1920x1080 source, TL/TR/BR/BL.
   const boards=[[[309,165],[565,293],[565,485],[303,386]],[[835,184],[1087,249],[1090,532],[833,499]],[[1623,269],[1752,146],[1779,396],[1628,460]],[[1310,434],[1422,365],[1428,642],[1318,680]]];
   for(let i=0;i<boards.length;i++){const q=boards[i].map(([x,y])=>[x/1920,y/1080]),canvas=makeCanvas(640,640),ctx=canvas.getContext('2d');ctx.fillStyle=C.slate;ctx.textAlign='center';ctx.textBaseline='middle';const lines=[['敬请','期待'],['COMING','SOON'],['下个版本','更强'],['明天见']][i];ctx.font=`900 ${i===1?77:100}px "${i===1?'Inter':'Noto Serif SC'}"`;lines.forEach((line,n)=>ctx.fillText(line,320,320+(n-(lines.length-1)/2)*130));const tx=state.own(new T.CanvasTexture(canvas));tx.colorSpace=T.SRGBColorSpace;
    const [a,b,c,d]=q,dx1=b[0]-c[0],dx2=d[0]-c[0],dy1=b[1]-c[1],dy2=d[1]-c[1],sx=a[0]-b[0]+c[0]-d[0],sy=a[1]-b[1]+c[1]-d[1],den=dx1*dy2-dx2*dy1,g=(sx*dy2-dx2*sy)/den,h=(dx1*sy-sx*dy1)/den,aa=b[0]-a[0]+g*b[0],bb=d[0]-a[0]+h*d[0],dd=b[1]-a[1]+g*b[1],ee=d[1]-a[1]+h*d[1];const positions=[],uv=[],indices=[],steps=16;
    for(let y=0;y<=steps;y++)for(let x=0;x<=steps;x++){const u=x/steps,v=y/steps,w=g*u+h*v+1,px=(aa*u+bb*v+a[0])/w,py=(dd*u+ee*v+a[1])/w;positions.push(...state.sourceAnchor(px,py,state.zAt(px,py)+.015).toArray());uv.push(u,1-v);if(x<steps&&y<steps){const k=y*(steps+1)+x;indices.push(k,k+steps+1,k+1,k+1,k+steps+1,k+steps+2);}}
    const geo=state.own(new T.BufferGeometry());geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));geo.setAttribute('uv',new T.Float32BufferAttribute(uv,2));geo.setIndex(indices);const mesh=new T.Mesh(geo,state.own(new T.MeshBasicMaterial({map:tx,transparent:true,depthTest:false,depthWrite:false,side:T.DoubleSide})));mesh.renderOrder=65;state.anchorGroup.add(mesh);
   }
   const clock=localPlane(state,labelCanvas('明天',{w:512,h:256,size:150}),1.9,.95,0,.15,.1);state.updates.push(f=>clock.mesh.rotation.x=Math.PI*(1-smooth((f-(52-shot.f0)+5)/5)));diagnostics.shots[id].billboards={method:'observed source hardware corners; projective homography subdivided into depth-registered mesh',corners:boards};
  }
  if(id==='S20'){
   const replyCanvas=makeCanvas(900,150),g=replyCanvas.getContext('2d'),reply=localPlane(state,replyCanvas,1,1,0,0,0);reply.mesh.material.depthTest=false;reply.mesh.renderOrder=85;
   state.afterCamera.push((f,p)=>{const frame=shot.f0+f,count=Math.max(0,Math.min(graphics.codeStrings.reply.length,1+Math.floor((frame-646)/1.2)));g.clearRect(0,0,900,150);g.fillStyle='rgba(250,249,245,.95)';g.beginPath();g.roundRect(0,0,900,150,36);g.fill();g.strokeStyle=C.clay;g.lineWidth=3;g.stroke();g.fillStyle=C.slate;g.font='500 57px "LXGW WenKai"';g.textBaseline='middle';g.fillText(graphics.codeStrings.reply.slice(0,count),35,76);reply.texture.needsUpdate=true;reply.mesh.visible=frame>=646&&frame<684;reply.mesh.material.opacity=1-smooth((frame-674)/10);const d=6,vh=2*d*Math.tan(camera.fov*Math.PI/360);reply.mesh.scale.set(vh*aspect*.43,vh*.127,1);reply.mesh.quaternion.copy(camera.quaternion);reply.mesh.position.set((.285-.5)*vh*aspect,(.5-.155)*vh,-d).applyQuaternion(camera.quaternion).add(camera.position);});
  }
  if(id==='S08a'){
   const tips=[[.184,.381],[.083,.740],[.176,.910],[.311,.952],[.432,.864]];
   for(let i=0;i<tips.length;i++){const [u,v]=tips[i],z=state.zAt(u,v)+.04,spark=sparkMesh(state,.32,.007,C.ivory);spark.position.copy(state.sourceAnchor(u,v,z));spark.traverse(o=>{if(o.isMesh){o.material.depthTest=false;o.material.transparent=true;o.renderOrder=70;o.userData.bloom=true;}});state.anchorGroup.add(spark);const glowCanvas=makeCanvas(128,128),gg=glowCanvas.getContext('2d'),gradient=gg.createRadialGradient(64,64,0,64,64,64);gradient.addColorStop(0,'rgba(255,218,164,.95)');gradient.addColorStop(.25,'rgba(255,132,80,.8)');gradient.addColorStop(1,'rgba(217,119,87,0)');gg.fillStyle=gradient;gg.fillRect(0,0,128,128);const glow=localPlane(state,glowCanvas,.9,.9,0,0,0);glow.mesh.position.copy(spark.position);glow.mesh.material.depthTest=false;glow.mesh.renderOrder=69;glow.mesh.userData.bloom=true;state.anchorGroup.add(glow.mesh);const base=spark.scale.clone();state.updates.push((f,p)=>{spark.scale.copy(base).multiplyScalar(.4+.6*smooth(Math.min(1,p*2+i*.1)));spark.rotation.z=p*.8+i;});}
   diagnostics.shots[id].fingertipSparks={sourceAnchors:tips,exactBrandGeometry:true,registered:true};
  }
  if(id==='S26')for(let i=0;i<7;i++){const bar=localPlane(state,labelCanvas('5.5',{w:256,h:512,size:95,family:'Newsreader',color:C.ivory,background:C.clay}),.72,1.2+i*.35,-3+i, -3+(1.2+i*.35)/2,.4);state.updates.push(f=>bar.mesh.scale.y=smooth((f-i*2.4)/8));}
  await installShotDetails({state,THREE:T,SVGLoader,assetMap,image,texture,raw,fail,worldW,worldH,width,height,glyphAtlas,localPlane,labelCanvas,sparkMesh,brand,diagnostics});
  state.dispose=()=>{for(const fn of state.disposeFns)fn();for(const r of state.owned)r.dispose();scene.clear();};
  return state;
  } catch(error) {for(const fn of state.disposeFns)fn();for(const r of state.owned)r.dispose();scene.clear();throw error;}
 }
 async function getState(shot){if(!states.has(shot.id)){const state=await build(shot);states.set(shot.id,state);if(states.size>2){const [key,old]=states.entries().next().value;if(key!==shot.id){old.dispose();states.delete(key);}}}return states.get(shot.id);}
 function sceneSample(state,local,duration){const p=clamp(local/Math.max(1,duration-1));state.rig.update(local,duration);const authoredPose={position:state.camera.position.clone(),quaternion:state.camera.quaternion.clone(),fov:state.camera.fov};for(const effect of state.effects){effect.update(local,p);if(!state.effectCameraOwner){state.camera.position.copy(authoredPose.position);state.camera.quaternion.copy(authoredPose.quaternion);state.camera.fov=authoredPose.fov;state.camera.updateProjectionMatrix();state.camera.updateMatrixWorld(true);}}for(const fn of state.updates)fn(local,p);if(state.parallax){const constraint=state.parallax.constrainCamera(state.camera);if(state.id==='S25'&&[0,Math.floor((duration-1)/2),duration-1].some(n=>Math.abs(local-n)<.001)){diagnostics.shots[state.id].layerFrames??={};diagnostics.shots[state.id].layerFrames[Math.round(local)]={...constraint,actualCamera:{position:state.camera.position.toArray(),quaternion:state.camera.quaternion.toArray(),fov:state.camera.fov}};}if(constraint.clamped){const d=diagnostics.shots[state.id];if(d.cameraClamps.length<20)d.cameraClamps.push({frame:local,...constraint});}state.parallax.update(state.camera);}for(const fn of state.afterCamera)fn(local,p);renderer.setClearColor(['S06','S08b'].includes(state.id)?C.slate:C.paper,1);renderer.render(state.scene,state.camera);}
 function composeMask(state){maskCtx.clearRect(0,0,width,height);if(state.maskMesh){state.parallax.group.updateMatrixWorld(true);state.maskMesh.matrixAutoUpdate=false;state.maskMesh.matrix.copy((state.maskTransform||state.parallax.group).matrixWorld);renderer.setClearColor(0,0);renderer.render(state.maskScene,state.camera);maskCtx.drawImage(renderer.domElement,0,0);}return state.maskMesh?maskCanvas:null;}
 async function renderFrame(frame){
  if(disposed)throw new Error('Film disposed');if(!Number.isInteger(frame)||frame<0||frame>=totalFrames)throw new Error(`Frame ${frame} outside 0..${totalFrames-1}`);
  let f=frame;if(frame>=totalFrames-12)f=totalFrames-12;const shot=shots.find(s=>f>=s.f0&&f<s.f1);if(!shot)throw new Error(`No shot owns frame ${frame}`);if(shot.id==='S10')f=shot.f0;
  if(f===0){out.fillStyle='#000';out.fillRect(0,0,width,height);return canvas;}
  const state=await getState(shot),local=f-shot.f0,duration=shot.f1-shot.f0,path=(cameraPaths.paths||cameraPaths)[shot.id],whip=/WHIP/i.test(path.move||shot.cam||''),samples=whip?6:1;
  ctx.clearRect(0,0,width,height);for(let i=0;i<samples;i++){const sample=Math.max(0,Math.min(duration-1,local+(i/(samples-1||1)-.5)*.5));sceneSample(state,sample,duration);ctx.globalAlpha=1/(i+1);ctx.drawImage(renderer.domElement,0,0);}ctx.globalAlpha=1;sceneSample(state,local,duration);
  const subjectMask=state.compositeMask?state.compositeMask(local,clamp(local/Math.max(1,duration-1))):composeMask(state);
  if(state.composite){state.composite(ctx,local,clamp(local/Math.max(1,duration-1)));if(state.parallax)state.parallax.group.visible=false;renderer.setClearColor(0,0);renderer.render(state.scene,state.camera);ctx.drawImage(renderer.domElement,0,0);if(state.parallax)state.parallax.group.visible=true;}
  // Three-frame drawing smears occur only on the authored odd dance half-beats.
  if(/^S36[bdfh]$/.test(shot.id)&&local<3){const snap=makeCanvas(width,height);snap.getContext('2d').drawImage(comp,0,0);ctx.save();for(let i=3;i>0;i--){ctx.globalAlpha=.09*(1-local/3);ctx.drawImage(snap,-i*width*.012,0,width*(1+i*.018),height);}ctx.restore();}
  ctx.save();if(shot.id==='S39'){const k=1+.02*smooth(local/Math.max(1,duration-13));ctx.translate(width/2,height/2);ctx.scale(k,k);ctx.translate(-width/2,-height/2);}graphics.draw(ctx,{frame:f,shot:shot.id==='S05'?{...shot,id:'S05_graphics'}:shot,localFrame:local,subjectMask,uiIn3D:true,drawLyrics:shot.id!=='S15'});if(shot.id==='S05'){const boxes=(state.a.features?.eyes||[]).map(([u,v,size])=>{const pt=state.sourceAnchor(u,v);if(state.parallax)pt.applyMatrix4(state.parallax.group.matrixWorld);pt.project(state.camera);return {x:(pt.x*.5+.5)*1920,y:(.5-pt.y*.5)*1080,r:Math.max(110,size*1920*2)};});const candidates=[[1190,700],[130,700],[1190,275],[130,140]];const overlap=([x,y])=>boxes.reduce((sum,e)=>sum+(x<e.x+e.r&&x+440>e.x-e.r&&y<e.y+e.r&&y+130>e.y-e.r?1:0),0);candidates.sort((a,b)=>overlap(a)-overlap(b));const [x,y]=candidates[0];ctx.save();ctx.scale(width/1920,height/1080);graphics.components.ChatBubble(ctx,{frame:f,x,y});ctx.restore();diagnostics.shots.S05.bubblePlacement={x,y,eyeBoxOverlaps:overlap([x,y])};}ctx.restore();
  if(shot.id==='S28b'&&local>=3){/* Infinity lives in the real 3D scene. */}
  if(shot.id==='S38'){out.clearRect(0,0,width,height);out.drawImage(local===0?state.mosaicHeroImage:comp,0,0,width,height);diagnostics.renderedFrames.push(frame);if(diagnostics.renderedFrames.length>256)diagnostics.renderedFrames.shift();return canvas;}
  const savedBackground=state.scene.background;state.scene.background=null;const visibility=[];state.scene.traverse(o=>{if(o.isMesh||o.isLine||o.isPoints){visibility.push([o,o.visible]);o.visible=o.visible&&!!o.userData.bloom;}});renderer.setClearColor(0,1);renderer.render(state.scene,state.camera);glowCanvas.getContext('2d').drawImage(renderer.domElement,0,0);for(const [o,visible] of visibility)o.visible=visible;state.scene.background=savedBackground;glowTexture.needsUpdate=true;
  let impactAge=-1;for(const start of IMPACT)if(f>=start&&f<start+3)impactAge=f-start;
  if(impactAge===0||(shot.id==='S20'&&local>=duration-2)){out.fillStyle='#fff';out.fillRect(0,0,width,height);return canvas;}
  let age=999;for(const k of onsets.kicks||[]){const kf=Math.round((typeof k==='number'?k:k.t)*fps);if(kf<=f)age=Math.min(age,f-kf);}
  postTexture.needsUpdate=true;postUniforms.shock.value=state.shock||0;postUniforms.shockActive.value=state.shockActive?1:0;postUniforms.frame.value=f;postUniforms.chorus.value=smooth((f-359)/8);postUniforms.impact.value=impactAge>0?2:0;postUniforms.pulse.value=f>=359&&shot.id!=='S10'&&f<totalFrames-12?Math.exp(-age/2.3):0;postRenderer.render(postScene,postCamera);out.drawImage(postRenderer.domElement,0,0);diagnostics.renderedFrames.push(frame);if(diagnostics.renderedFrames.length>256)diagnostics.renderedFrames.shift();return canvas;
 }
 return {canvas,renderFrame,diagnostics,dispose(){disposed=true;for(const s of states.values())s.dispose();for(const r of resources)r.dispose();renderer.dispose();postRenderer.dispose();images.clear();textures.clear();states.clear();}};
}
