/** Targeted deterministic art passes. No hidden asset substitution. */
import {seededRandom} from './effects.mjs';
const clamp=x=>Math.max(0,Math.min(1,x)),ease=x=>{x=clamp(x);return x*x*(3-2*x);};
export function matchIrisTransform(anchor,target,width,height){if(!anchor||anchor.length<3||!(anchor[2]>0))throw new Error('Match zoom needs [u,v,irisRadiusWidth]');const scale=target.radius/(anchor[2]*width);return {scale,x:target.x-anchor[0]*width*scale,y:target.y-anchor[1]*height*scale};}
export async function installShotDetails({state:s,THREE:T,SVGLoader,assetMap,image,texture,raw,fail,worldW,worldH,width,height,glyphAtlas,localPlane,labelCanvas,sparkMesh,brand,diagnostics}){
 const initialObjects=new Set(s.scene.children);const id=s.id,a=s.a,rnd=seededRandom(5514),notes=diagnostics.shots[id].unverified;
 const need=(value,key)=>{if(value)return value;if(assetMap.diagnosticMissing){notes.push('DIAGNOSTIC OMITTED: '+key);diagnostics.finalApproval=false;return null;}fail(id,key);};
 const point=([u,v],z)=>s.sourceAnchor?s.sourceAnchor(u,v,z??s.zAt(u,v)+.025):new T.Vector3((u-.5)*worldW,(.5-v)*worldH,z??.35);
 const mat=(color,options={})=>s.own(new T.MeshBasicMaterial({color,side:T.DoubleSide,...options}));
 function line(vertices,color='#D97757',opacity=.65){const g=s.own(new T.BufferGeometry().setFromPoints(vertices)),m=s.own(new T.LineBasicMaterial({color,transparent:true,opacity})),o=new T.Line(g,m);s.scene.add(o);return o;}
 function glyphCloud(count){const g=s.own(new T.PlaneGeometry(.18,.18));g.setAttribute('tile',new T.InstancedBufferAttribute(Float32Array.from({length:count},(_,i)=>i%64),1));const m=s.own(new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,uniforms:{atlas:{value:glyphAtlas},opacity:{value:1}},vertexShader:'attribute float tile;varying vec2 vUv;void main(){vUv=(vec2(mod(tile,8.),7.-floor(tile/8.))+uv)/8.;gl_Position=projectionMatrix*modelViewMatrix*instanceMatrix*vec4(position,1.);}',fragmentShader:'uniform sampler2D atlas;uniform float opacity;varying vec2 vUv;void main(){gl_FragColor=texture2D(atlas,vUv)*vec4(1.,.7,.53,opacity);\n#include <colorspace_fragment>\n}'}));const mesh=new T.InstancedMesh(g,m,count);mesh.frustumCulled=false;s.scene.add(mesh);return mesh;}
 if(id==='S03'){
  const currents=[];for(let stream=0;stream<4;stream++)for(let staff=0;staff<5;staff++){const verts=Array.from({length:100},(_,j)=>{const x=(j/99-.5)*worldW*1.25;return new T.Vector3(x,Math.sin(x*.45+stream)*.5+(staff-2)*.11+(stream-1.5)*2,stream*.3-1);});currents.push(line(verts,stream%2?'#F0EEE6':'#D97757',.15));}s.updates.push((f,p)=>currents.forEach((o,i)=>{o.position.x=Math.sin(p*2+i*.1)*.25;o.position.y=Math.sin(p+i*.3)*.08;}));
 }
 if(id==='S13'){
  // Each paper bird is two hinged triangles, not a flashing billboard.
  const birds=[];for(let i=0;i<64;i++){const group=new T.Group(),w=.09+rnd()*.13;for(const side of [-1,1]){const g=s.own(new T.BufferGeometry());g.setAttribute('position',new T.Float32BufferAttribute([0,0,0,side*w,.025,-.07,0,0,-.20],3));g.computeVertexNormals();const wing=new T.Mesh(g,mat(i%5?'#FAF9F5':'#D97757'));group.add(wing);}const base=new T.Vector3((rnd()-.5)*worldW,(rnd()-.5)*worldH,-2+rnd()*4);s.scene.add(group);birds.push({group,base,speed:.5+rnd(),phase:rnd()*6.28});}s.updates.push((f,p)=>birds.forEach(b=>{b.group.position.copy(b.base).add(new T.Vector3(Math.sin(p*3+b.phase)*.5,p*3*b.speed,0));b.group.rotation.z=.15*Math.sin(p*4+b.phase);b.group.children.forEach((w,i)=>w.rotation.z=(i?1:-1)*(.2+Math.sin(f*.4+b.phase)*.6));}));notes.push('Bird flock is procedural hinged-paper geometry; depth mask review remains necessary.');
 }
 if(id==='S14'){
  const mouth=need(a.features?.mouth,'features.mouth [u,v]');if(mouth){const end=point(mouth,.55),curve=new T.CatmullRomCurve3([new T.Vector3(-worldW*.5,-1,-1),new T.Vector3(-3,1.8,.4),new T.Vector3(end.x-1,end.y+.2,1.3),end]),mesh=glyphCloud(360),dummy=new T.Object3D();s.updates.push((f,p)=>{for(let i=0;i<360;i++){const u=((i/360+p*.95)%1),v=curve.getPoint(u),spread=(1-u)*.22;dummy.position.copy(v).add(new T.Vector3(Math.sin(i*4.1)*spread,Math.cos(i*2.3)*spread,Math.sin(i)*spread));dummy.quaternion.copy(s.camera.quaternion);if(s.parallax)dummy.quaternion.premultiply(s.parallax.group.getWorldQuaternion(new T.Quaternion()).invert());dummy.scale.setScalar(.35+.65*(1-u));dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);}mesh.instanceMatrix.needsUpdate=true;});}
 }
 if(id==='S15'){
  const data=JSON.parse(await raw('assets/brand/brush-changkuai.json')),c=document.createElement('canvas');c.width=1300;c.height=650;const g=c.getContext('2d'),mask=document.createElement('canvas');mask.width=c.width;mask.height=c.height;const mg=mask.getContext('2d');
  const outlines=data.glyphs.map(v=>({path:new Path2D(v.d),contours:(v.d.match(/M[^M]+/g)||[]).map(d=>{const svg=document.createElementNS('http://www.w3.org/2000/svg','path');svg.setAttribute('d',d);return {path:new Path2D(d),length:svg.getTotalLength()};})}));
  const ink=localPlane(s,c,worldW*.62,worldH*.42,0,-2.2,1.1);ink.mesh.renderOrder=25;
  s.updates.push((f,p)=>{g.clearRect(0,0,c.width,c.height);mg.clearRect(0,0,c.width,c.height);outlines.forEach((glyph,index)=>{const q=clamp((f-index*2)/10),sc=.54;mg.save();mg.translate(70+index*580,50);mg.scale(sc,sc);mg.lineJoin='round';mg.lineCap='round';mg.strokeStyle='#fff';glyph.contours.forEach((contour,j)=>{mg.lineWidth=95+42*Math.sin(j*1.7);mg.setLineDash([contour.length,contour.length]);mg.lineDashOffset=contour.length*(1-q);mg.stroke(contour.path);});mg.setLineDash([]);if(q===1)mg.fill(glyph.path);mg.restore();g.save();g.translate(70+index*580,50);g.scale(sc,sc);g.fillStyle='#D97757';g.fill(glyph.path);g.restore();});g.globalCompositeOperation='destination-in';g.drawImage(mask,0,0);g.globalCompositeOperation='source-atop';for(let k=0;k<600;k++){g.fillStyle='rgba(80,40,25,.045)';g.fillRect((k*137)%1300,(k*73)%650,1,4);}g.globalCompositeOperation='source-over';ink.texture.needsUpdate=true;s.shock=clamp((s.shot.f0+f-Math.round(16.74*30))/12);s.shockActive=s.shot.f0+f>=Math.round(16.74*30);});notes.push('BrushWrite uses exact LXGW outline paths and variable-width contour stroke-dash masks; authored handwriting stroke order is not reconstructed.');
 }
 if(id==='S17'||id==='S30'){
  const anchor=need(id==='S17'?a.features?.contact:a.features?.surface,id==='S17'?'features.contact [u,v]':'features.surface [u,v]');
  if(anchor){const origin=point(anchor,.4),rings=[];for(let i=0;i<5;i++){const g=s.own(new T.RingGeometry(.98,1,100)),o=new T.Mesh(g,mat('#D97757',{transparent:true,opacity:.4,depthWrite:false}));o.position.copy(origin);o.scale.y=.25;s.scene.add(o);rings.push(o);}const glyph=id==='S17'?glyphCloud(80):null,dummy=new T.Object3D();const grasses=[];
   if(id==='S17')for(let i=0;i<80;i++){const blade=new T.Mesh(s.own(new T.PlaneGeometry(.02,.28)),mat('#788C5D',{transparent:true}));const x=(rnd()-.5)*4,y=(rnd()-.5)*.7;blade.position.copy(origin).add(new T.Vector3(x,y+.14,.02));blade.rotation.z=(rnd()-.5)*.5;s.scene.add(blade);grasses.push({blade,at:rnd()*.5});}
   s.updates.push((f,p)=>{rings.forEach((o,i)=>{const age=id==='S17'?p-i*.12:(p*1.3-i*.16)%1,progress=clamp(age);o.visible=age>=0;o.scale.set((.2+progress*4),(.2+progress*4)*.23,1);o.material.opacity=(1-progress)*.48;if(id==='S30')o.position.x=origin.x+(p-i*.15)*3;});if(glyph){for(let i=0;i<80;i++){const angle=i/80*Math.PI*2,r=.2+p*4;dummy.position.set(origin.x+Math.cos(angle)*r,origin.y+Math.sin(angle)*r*.23,origin.z+.03);dummy.quaternion.copy(s.camera.quaternion);if(s.parallax)dummy.quaternion.premultiply(s.parallax.group.getWorldQuaternion(new T.Quaternion()).invert());dummy.scale.setScalar(.7);dummy.updateMatrix();glyph.setMatrixAt(i,dummy.matrix);}glyph.instanceMatrix.needsUpdate=true;glyph.material.uniforms.opacity.value=1-p;}grasses.forEach(({blade,at})=>{blade.scale.y=ease((p-at)*3);blade.visible=p>=at;});});notes.push(id==='S17'?'Contact ripple/grass remain near annotated floor anchor; below-knee masking requires plate review.':'Surface ripple trail follows annotated plane, not generated-wave optical flow.');}
 }
 if(id==='S28c'){
  const geo=s.own(new T.PlaneGeometry(.07,.12)),palette=['#D97757','#6A9BCB','#788C5D','#C46686','#E3DACC'],parts=[];for(let i=0;i<180;i++){const o=new T.Mesh(geo,mat(palette[i%5],{transparent:true}));s.scene.add(o);parts.push({o,x:(rnd()-.5)*2,y:rnd()*1.8+.3,z:(rnd()-.5)*2,spin:rnd()*10});}s.updates.push((f,p)=>parts.forEach(v=>{const t=p*2;v.o.position.copy(s.cloudOrigin||new T.Vector3(0,1.8,.4)).add(new T.Vector3(v.x*t,v.y*t-.9*t*t,v.z*t));v.o.rotation.set(t*v.spin,t*v.spin*.7,t);v.o.material.opacity=1-clamp((p-.8)/.2);}));
 }
 if(id==='S06'){
  const silhouette=need(assetMap.silhouette,'assetMap.silhouette (real character alpha)');if(silhouette){const im=await image(silhouette,id,'silhouette'),c=document.createElement('canvas');c.width=256;c.height=256*im.height/im.width;const g=c.getContext('2d');g.drawImage(im,0,0,c.width,c.height);const pixels=g.getImageData(0,0,c.width,c.height),targets=[];let alphaCount=0;for(let k=3;k<pixels.data.length;k+=4)if(pixels.data[k]>170)alphaCount++;if(alphaCount/(pixels.data.length/4)>.95)throw new Error('S06 silhouette is effectively opaque; real cutout alpha is required');for(let n=0;n<100000&&targets.length<2400;n++){const x=Math.floor(rnd()*c.width),y=Math.floor(rnd()*c.height);if(pixels.data[(y*c.width+x)*4+3]>170)targets.push([(x/c.width-.5)*4,(.5-y/c.height)*4.8]);}if(targets.length<2400)throw new Error('S06 silhouette has insufficient nonzero alpha');const fx=s.effects.find(e=>e.metadata.name==='TokenTunnel'),mesh=fx.root.children.find(o=>o.isInstancedMesh),matrix=new T.Matrix4(),pos=new T.Vector3(),q=new T.Quaternion(),scale=new T.Vector3();s.updates.push((f,p)=>{const k=ease((p-.35)/.6);for(let i=0;i<2400;i++){mesh.getMatrixAt(i,matrix);matrix.decompose(pos,q,scale);const target=new T.Vector3(targets[i][0],targets[i][1],-5).applyQuaternion(s.camera.quaternion).add(s.camera.position);pos.lerp(target,k);q.copy(s.camera.quaternion);scale.lerp(new T.Vector3(.065,.065,1),k);matrix.compose(pos,q,scale);mesh.setMatrixAt(i,matrix);}mesh.instanceMatrix.needsUpdate=true;});}
 }
 if(id==='S18'){
  const handPath=need(a.support?.hand?.path,'support.hand.path (transparent human hand)'),touch=need(a.features?.touch,'features.touch [u,v]');
  if(handPath&&touch){const im=await image(handPath,id,'hand'),hand=localPlane(s,im,worldW,worldH,0,0,.7),tip=need(a.support.hand.tip,'support.hand.tip [u,v]');if(tip){const z=s.zAt(...touch)+.03,dest=point(touch,z),scale=s.sourceScale(z),tipP=new T.Vector3((tip[0]-.5)*worldW*scale,(.5-tip[1])*worldH*scale,0),delta=dest.clone().sub(tipP);hand.mesh.scale.setScalar(scale);hand.mesh.material.depthTest=false;hand.mesh.renderOrder=70;s.updates.push((f,p)=>{const k=ease(p);hand.mesh.position.set(delta.x+(1-k)*1.1,delta.y-(1-k)*.3,z);});notes.push('Hand tip lands on annotated touch point at local last frame (global 604); visual fingertip continuity to frame605 remains unapproved.');}}
 }
 if(id==='S36f'){
  const center=a.features?.tie?.slice(0,2)||[.5,.5],spark=sparkMesh(s,worldW*.55,.025);spark.position.copy(point(center,.3));spark.traverse(o=>{if(o.isMesh){o.material.transparent=true;o.material.opacity=.88;o.material.depthTest=false;o.renderOrder=20;}});const base=spark.scale.clone();s.updates.push((f,p)=>spark.scale.copy(base).multiplyScalar(.15+.85*ease(f/3)));notes.push('Large exact brand spark grows behind actor over first3frames; subject matte restores actor over rays.');
 }
 if(id==='S33'){
  const sun=need(a.features?.sun,'features.sun [u,v,rWidth]');if(sun){const mask=document.createElement('canvas');mask.width=512;mask.height=512;const g=mask.getContext('2d');g.fillStyle='#D4A27F';g.beginPath();g.arc(256,256,255,0,Math.PI*2);g.fill();g.globalCompositeOperation='destination-out';g.drawImage(brand.image,0,0,512,512);g.globalCompositeOperation='source-over';const clouds=localPlane(s,mask,sun[2]*2*worldW,sun[2]*2*worldW,(sun[0]-.5)*worldW,(.5-sun[1])*worldH,.25);clouds.mesh.material.depthTest=false;clouds.mesh.renderOrder=30;clouds.mesh.position.copy(point(sun,.25));clouds.mesh.scale.setScalar(s.sourceScale(.25));s.updates.push((f,p)=>clouds.mesh.material.opacity=.45*ease(p*2));notes.push('Exact SVG aperture dims outer sun sectors with warm code cloud mask; actual disc alignment and trio matte need frame review.');}
 }
 if(['S36e','S36h'].includes(id)){
  const key=id==='S36e'?'cross':'point',anchor=need(a.features?.[key],`features.${key} [u,v]`);if(anchor){const center=point(anchor,.35),geometry=s.own(new T.RingGeometry(.94,1,96)),ring=new T.Mesh(geometry,mat('#D97757',{transparent:true,depthTest:false,depthWrite:false}));ring.position.copy(center);ring.renderOrder=60;s.scene.add(ring);s.updates.push((f,p)=>{const radius=id==='S36e'?.12+p*1.1:.08+p*.55;ring.scale.setScalar(radius);ring.material.opacity=(1-p)*.75;});}
 }
 if(id==='S36b'){
  const anchor=need(a.features?.wrist,'features.wrist [u,v]');if(anchor){const center=point(anchor,.4),trail=[];for(let i=0;i<9;i++){const sp=sparkMesh(s,.05+.04*(1-i/9),.002);sp.traverse(o=>{if(o.isMesh){o.material.transparent=true;o.material.depthTest=false;o.renderOrder=60;}});trail.push(sp);}s.updates.push((f,p)=>trail.forEach((sp,i)=>{const q=Math.max(0,p-i*.05);sp.position.copy(center).add(new T.Vector3(q*.5-i*.05,Math.sin(q*3)*.16-i*.025,0));sp.visible=f>=i*.3;sp.traverse(o=>{if(o.isMesh)o.material.opacity=(1-i/10)*(1-p*.6);});}));}
 }
 if(id==='S37'){
  const bust=need(a.support?.bust?.path,'support.bust.path'),wide=need(a.support?.wide?.path,'support.wide.path'),iris=need(a.features?.iris,'features.iris [u,v,r]'),bi=need(a.support?.bust?.iris,'support.bust.iris [u,v,r]'),wi=need(a.support?.wide?.iris,'support.wide.iris [u,v,r]'),reflection=need(assetMap.reflectionAtlas,'assetMap.reflectionAtlas (S01–S36 firstpass)'),eyeMask=need(a.mask,'mask (eye source matte)'),bustMask=need(a.support?.bust?.mask,'support.bust.mask'),wideMask=need(a.support?.wide?.mask,'support.wide.mask');
  if(bust&&wide&&iris&&bi&&wi&&reflection&&eyeMask&&bustMask&&wideMask){
   s.ornaments?.forEach(o=>o.visible=false);if(!(iris[2]>bi[2]&&bi[2]>wi[2]&&wi[2]>0))throw new Error('S37 iris radii must strictly decrease eye > bust > wide');
   const ims=await Promise.all([image(a.plate,id,'eye'),image(bust,id,'bust'),image(wide,id,'wide'),image(reflection,id,'reflectionAtlas')]);
   const canvas=(w=width,h=height)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c;},ivorySpark=canvas(256,256),sparkContext=ivorySpark.getContext('2d');sparkContext.drawImage(brand.image,0,0,256,256);sparkContext.globalCompositeOperation='source-in';sparkContext.fillStyle='#FAF9F5';sparkContext.fillRect(0,0,256,256);
   const maskImages=await Promise.all([image(eyeMask,id,'eye matte'),image(bustMask,id,'bust matte'),image(wideMask,id,'wide matte')]);
   const mattes=maskImages.map(im=>{const c=canvas(im.width,im.height),g=c.getContext('2d');g.drawImage(im,0,0);const px=g.getImageData(0,0,c.width,c.height);for(let i=0;i<px.data.length;i+=4){const alpha=Math.round(px.data[i]*px.data[i+3]/255);px.data[i]=px.data[i+1]=px.data[i+2]=255;px.data[i+3]=alpha;}g.putImageData(px,0,0);return c;});
   const featureSets=[a.features,a.support.bust.features||{},a.support.wide.features||{}];
   const views=ims.slice(0,3).map((im,index)=>{const c=canvas(im.width,im.height),g=c.getContext('2d'),features=featureSets[index];g.drawImage(im,0,0);if(features.halo){const [u,v,w,h]=features.halo;g.strokeStyle='#D97757';g.lineWidth=Math.max(1,im.width*.0015);g.beginPath();g.ellipse(u*im.width,v*im.height,w*im.width/2,h*im.height/2,0,0,Math.PI*2);g.stroke();const subject=canvas(im.width,im.height),sg=subject.getContext('2d');sg.drawImage(im,0,0);sg.globalCompositeOperation='destination-in';sg.drawImage(mattes[index],0,0,im.width,im.height);g.drawImage(subject,0,0);}for(const [u,v,size] of features.eyes||[])g.drawImage(ivorySpark,(u-size/2)*im.width,v*im.height-size*im.width/2,size*im.width,size*im.width);for(const anchor of [features.hairpin,features.tie].filter(Boolean)){const [u,v,size]=anchor;g.drawImage(brand.image,(u-size/2)*im.width,v*im.height-size*im.width/2,size*im.width,size*im.width);}return c;});
   const registeredMask=canvas(),outgoing=canvas(),outgoingMask=canvas(),portalMask=canvas();
   const registration=p=>{const split=Math.log(bi[2]/iris[2])/Math.log(wi[2]/iris[2]),stage=p<split?0:1,t=stage===0?p/split:(p-split)/(1-split),from=stage,to=stage+1,anchors=[iris,bi,wi],q=ease(p),center={x:(iris[0]*(1-q)+wi[0]*q)*width,y:(iris[1]*(1-q)+wi[1]*q)*height},radius=iris[2]*width*Math.pow(wi[2]/iris[2],p),target={...center,radius},tf=matchIrisTransform(anchors[from],target,width,height),tt=matchIrisTransform(anchors[to],target,width,height),edge=Math.min(center.x-tf.x,tf.x+width*tf.scale-center.x,center.y-tf.y,tf.y+height*tf.scale-center.y),portal=Math.max(0,Math.min(edge*.92,radius*(.92+6*(1-ease(t/.35))))*(1-ease((t-.55)/.45)));return {from,to,center,radius,tf,tt,portal,progress:p};};
   const prepare=p=>{const r=registration(p),pg=portalMask.getContext('2d'),og=outgoing.getContext('2d'),mg=outgoingMask.getContext('2d');pg.clearRect(0,0,width,height);if(r.portal>.01){const gradient=pg.createRadialGradient(r.center.x,r.center.y,r.portal*.68,r.center.x,r.center.y,r.portal);gradient.addColorStop(0,'rgba(255,255,255,1)');gradient.addColorStop(1,'rgba(255,255,255,0)');pg.fillStyle=gradient;pg.fillRect(0,0,width,height);}for(const [g,source] of [[og,views[r.from]],[mg,mattes[r.from]]]){g.clearRect(0,0,width,height);g.globalCompositeOperation='source-over';g.drawImage(source,r.tf.x,r.tf.y,width*r.tf.scale,height*r.tf.scale);g.globalCompositeOperation='destination-in';g.drawImage(portalMask,0,0);g.globalCompositeOperation='source-over';}return r;};
   s.compositeMask=(f,p)=>{const r=prepare(p),g=registeredMask.getContext('2d');g.clearRect(0,0,width,height);g.drawImage(mattes[r.to],r.tt.x,r.tt.y,width*r.tt.scale,height*r.tt.scale);g.globalCompositeOperation='destination-out';g.drawImage(outgoing,0,0);g.globalCompositeOperation='source-over';g.drawImage(outgoingMask,0,0);return registeredMask;};
   s.composite=(ctx,f,p)=>{const r=prepare(p);ctx.fillStyle='#FAF9F5';ctx.fillRect(0,0,width,height);ctx.drawImage(views[r.to],r.tt.x,r.tt.y,width*r.tt.scale,height*r.tt.scale);ctx.drawImage(outgoing,0,0);ctx.save();ctx.beginPath();ctx.ellipse(r.center.x,r.center.y,r.radius,r.radius*.86,0,0,Math.PI*2);ctx.clip();ctx.globalAlpha=.58*(1-p);ctx.drawImage(ims[3],r.center.x-r.radius,r.center.y-r.radius*.86,r.radius*2,r.radius*1.72);ctx.restore();};
   notes.push('Iris portal is feathered, bounded inside outgoing source, shrinks inside iris by35%ofeachstage and disappears fully at stageend. Final wide registration is exactly source-full-frame; source-specific observed ornaments restored. Actual identity seam review still required.');
   diagnostics.shots[id].matchZoom={anchors:[iris,bi,wi],method:'continuous exponential registered pullout with feathered iris-only disappearing portal',matteSources:[eyeMask,bustMask,wideMask],maskRegistration:'same radial alpha and transforms as RGB',finalWideTransform:registration(1).tt,actualSeamQA:'pending'};
  }
 }
 if(['S14','S17','S18','S28c','S30','S33','S36b','S36e','S36f','S36h'].includes(id)&&s.parallax){for(const object of [...s.scene.children])if(!initialObjects.has(object))s.parallax.group.add(object);}

}
