'use strict';
/* Original First Day film renderer. Absolute-time animation; seeded procedural geometry.
   No production imagery or source borrowed from reference films. */
const W=1920,H=1080,canvas=document.querySelector('#film'),c=canvas.getContext('2d',{alpha:false});
const TAU=Math.PI*2,clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),lerp=(a,b,k)=>a+(b-a)*k;
const ease=x=>{x=clamp(x);return x*x*(3-2*x)},out=x=>1-Math.pow(1-clamp(x),3);
const hash=(n,s=0)=>{let v=Math.sin(n*127.1+s*311.7)*43758.5453123;return v-Math.floor(v)};
const palettes={jade:['#071820','#65ddd0','#fff3cf','#ed9266'],night:['#080a21','#7b8cff','#fdf0da','#ff927f'],day:['#f4efdf','#2551a0','#fff9e6','#cfaa68'],rose:['#210f30','#e494c1','#fff4d9','#87d7ec'],gold:['#141129','#ecc975','#fff8df','#98bfe9']};
let config={},assets={videos:{},sprites:{},plates:{}},errors=[],proceduralBackground=null,frameTime=0,audioReactive=false,audioScales={};
// Features are measured bands of the full mix; these helpers do not identify instruments or verified beats.
function envelopeAt(t,band='mix'){const a=config.audioFeatures?.rms_envelopes?.[band]||[],fps=config.audioFeatures?.envelopes_fps||100;if(!a.length)return 0;const x=clamp(t*fps,0,a.length-1),i=Math.floor(x),k=x-i;return lerp(a[i],a[Math.min(i+1,a.length-1)],k)}
function attackAt(t,band='mix',halfLife=.11){const events=config.audioFeatures?.onsets?.[band]||[];let lo=0,hi=events.length;while(lo<hi){const mid=(lo+hi)>>1;if(events[mid][0]<=t)lo=mid+1;else hi=mid}let v=0;for(let i=lo-1;i>=0;i--){const age=t-events[i][0];if(age>halfLife*8)break;v=Math.max(v,events[i][1]*Math.pow(.5,age/halfLife))}return clamp(v/(audioScales[band]?.attack||1))}
function envelopeLevel(t,band='mix'){return clamp(envelopeAt(t,band)/(audioScales[band]?.envelope||1))}
function danceIndex(t){const r=config.rhythm;if(!r?.bpm)return Math.floor(t*6);const step=60/r.bpm/(r.subdivisions||2);return Math.floor((t-(r.phase||0))/step+1e-9)}
window.attackAt=attackAt;window.envelopeAt=envelopeAt;
function seat(id){const ids=Object.keys(config.modelNames||{}),i=Math.max(0,ids.indexOf(id)),row=Math.floor(i/8),col=i%8;return{x:260+col*200+(row%2)*40,y:450+row*130,h:150}}
function seated(ids,t,p,omit=[]){for(const id of ids){if(omit.includes(id))continue;const q=seat(id);c.save();c.globalAlpha=.68;sprite(id,q.x,q.y,q.h,t,{cadence:12,still:true,shadow:false});c.restore()}}
const cfgURL=new URL(new URLSearchParams(location.search).get('config')||'../config.json',location.href);
function resolveAsset(v){const s=typeof v==='string'?v:v.url;return new URL(s,cfgURL).href}
function ellipse(x,y,rx,ry,fill){c.fillStyle=fill;c.beginPath();c.ellipse(x,y,Math.max(.01,rx),Math.max(.01,ry),0,0,TAU);c.fill()}
function line(points,col,width=1){c.strokeStyle=col;c.lineWidth=width;c.beginPath();points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.stroke()}
function poly(points,fill){c.fillStyle=fill;c.beginPath();points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();c.fill()}
function glow(x,y,r,col,strength=1){c.save();c.globalAlpha=clamp(strength*(audioReactive?(.9+.18*attackAt(frameTime,'mix')+.07*envelopeLevel(frameTime,'low')):1));const g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,col);g.addColorStop(1,col+'00');ellipse(x,y,r,r,g);c.restore()}
function type(txt,x,y,size=40,color='#fff',align='center',weight=500){c.fillStyle=color;c.font=`${weight} ${size}px "PingFang SC","Noto Sans CJK SC","Microsoft YaHei",sans-serif`;c.textAlign=align;c.textBaseline='middle';c.fillText(txt,x,y);const m=c.measureText(txt),tr=c.getTransform(),pad=Math.ceil(c.shadowBlur*2+Math.max(Math.abs(c.shadowOffsetX),Math.abs(c.shadowOffsetY)));const l=x-m.actualBoundingBoxLeft,r=x+m.actualBoundingBoxRight,top=y-m.actualBoundingBoxAscent,bottom=y+m.actualBoundingBoxDescent;const corners=[[l,top],[r,top],[r,bottom],[l,bottom]].map(([xx,yy])=>({x:tr.a*xx+tr.c*yy+tr.e,y:tr.b*xx+tr.d*yy+tr.f}));const xs=corners.map(q=>q.x),ys=corners.map(q=>q.y);(window.textBoxes??=[]).push({text:txt,x:Math.min(...xs)-pad,y:Math.min(...ys)-pad,width:Math.max(...xs)-Math.min(...xs)+2*pad,height:Math.max(...ys)-Math.min(...ys)+2*pad,font:c.font,alpha:c.globalAlpha,shadowPadding:pad})}
function cover(img,x=0,y=0,w=W,h=H){const iw=img.videoWidth||img.naturalWidth||img.width,ih=img.videoHeight||img.naturalHeight||img.height;if(!iw||!ih)return;const k=Math.max(w/iw,h/ih);c.drawImage(img,x+(w-iw*k)/2,y+(h-ih*k)/2,iw*k,ih*k)}
function project(x,y,z,cam={x:0,y:0,z:0,roll:0,f:850}){const zz=z-cam.z;if(zz<20)return null;const xx=x-cam.x,yy=y-cam.y,k=cam.f/zz,co=Math.cos(cam.roll||0),si=Math.sin(cam.roll||0);return{x:W/2+(xx*co-yy*si)*k,y:H/2+(xx*si+yy*co)*k,k,z:zz}}
function vignette(amount=.4){const g=c.createRadialGradient(W*.5,H*.44,H*.1,W*.5,H*.5,W*.7);g.addColorStop(0,'#00000000');g.addColorStop(1,`rgba(0,0,0,${amount})`);c.fillStyle=g;c.fillRect(0,0,W,H)}
function grain(t,amount=.025){c.save();c.globalAlpha=amount;for(let i=0;i<220;i++){const x=hash(i,Math.floor(t*24))*W,y=hash(i+431,Math.floor(t*24))*H;c.fillStyle=i%2?'#fff':'#000';c.fillRect(x,y,1+hash(i,7)*3,1)}c.restore()}
function backdrop(p,t,kind='night'){c.fillStyle=p[0];c.fillRect(0,0,W,H);const g=c.createLinearGradient(0,0,W,H);g.addColorStop(0,p[0]);g.addColorStop(.5,p[0]);g.addColorStop(1,p[1]+'38');c.fillStyle=g;c.fillRect(0,0,W,H);if(kind!=='day'){for(let i=0;i<110;i++){c.globalAlpha=.15+.45*hash(i,11);ellipse(hash(i,2)*W,(hash(i,3)*H+t*(hash(i,4)*9+2))%H,.5+hash(i,5),.5+hash(i,5),p[2])}c.globalAlpha=1}}
function dust(t,p,amount=120,depth=0){c.save();for(let i=0;i<amount;i++){const age=(t*.18+hash(i,12))%1,z=hash(i,14);if(depth&&((z>.5)!==(depth>0)))continue;const x=(hash(i,8)*W+Math.sin(t*.5+i)*30),y=H*(1-age),r=(1+z*3);c.globalAlpha=Math.sin(age*Math.PI)*(.1+z*.4)*(audioReactive?(.88+.24*attackAt(t,'high',.08)):1);ellipse(x,y,r,r,p[i%3?2:3])}c.restore()}
const poseMetrics={gpt_dance_a:{waist:[185,212],head:69},gpt_dance_b:{waist:[203,234],head:68},deepseek_dance_a:{waist:[233,194],head:62},deepseek_dance_b:{waist:[289,231],head:64}};
function sprite(id,x,y,height,t,opts={}){let actual=id;if(opts.dance&&(id==='gpt'||id==='deepseek'))actual=id+'_dance_'+(((danceIndex(frameTime)%2)+2)%2?'b':'a');if(opts.unfold&&id==='future')actual='future_open';const img=assets.sprites[actual]||assets.sprites[id];if(!img)return false;const cadence=opts.cadence||60,qt=Math.floor(t*cadence)/cadence,bob=opts.still?0:Math.sin(qt*3.8+(opts.seed||0))*(opts.bob??6);const iw=img.naturalWidth,ih=img.naturalHeight,w=height*iw/ih;c.save();c.globalAlpha=opts.alpha??1;c.translate(x,y+bob);c.rotate(opts.angle||0);c.scale(opts.flip?-1:1,1);if(opts.shadow===true){c.save();c.globalAlpha*=.24;ellipse(0,0,w*.29,12,'#050711');c.restore()}const met=poseMetrics[actual];if(met){const k=height*.128/met.head;c.drawImage(img,-met.waist[0]*k,-height*.5-met.waist[1]*k,iw*k,ih*k)}else c.drawImage(img,-w/2,-height,w,height);c.restore();return true}
function cast(sh,t,poses){const ids=(sh.cast||[]).slice(-Math.max(1,poses?poses.length:6));ids.forEach((id,i)=>{const p=poses?poses[i%poses.length]:{x:W*(i+1)/(ids.length+1),y:880,h:650};sprite(id,p.x,p.y,p.h,t,{cadence:sh.cadence||60,seed:i,alpha:p.alpha??1,angle:p.angle||0,bob:p.bob??5,dance:sh.params?.dance,unfold:sh.params?.state==='future_unfolds'});if(sh.modelLabels!==false)type((config.modelNames||{})[id]||id,p.x,p.y+44,26,p.color||'#fff4df')})}
function fan(x,y,r,t,opening,col,rotation=0){c.save();c.translate(x,y);c.rotate(rotation);const n=28,spread=lerp(.035,Math.PI*.87,opening);for(let i=n-1;i>=0;i--){const a=-Math.PI/2-spread/2+spread*i/(n-1),b=a+spread/(n-1)*1.04;const rr=r*(.96+.04*Math.cos(i*1.5));const pts=[[0,0],[Math.cos(a)*rr,Math.sin(a)*rr],[Math.cos(b)*rr,Math.sin(b)*rr]];poly(pts,i%2?col[2]:col[1]);c.save();c.globalAlpha*=.35;line([[0,0],pts[1]],col[0],1);c.restore()}ellipse(0,0,r*.026,r*.026,col[3]);c.restore()}
function ribbons(t,p,origin={x:960,y:610},count=20,spread=1){c.save();c.globalCompositeOperation='screen';for(let j=0;j<count;j++){const phase=hash(j,23)*TAU,pts=[];for(let n=0;n<=52;n++){const u=n/52,a=u*TAU*1.25+phase+t*.44;pts.push([origin.x+Math.sin(a)*(150+u*680)*spread,origin.y+(u-.5)*800+Math.cos(a*.7)*65])}c.globalAlpha=.08+.3*hash(j,17);line(pts,p[j%2?1:3],1+hash(j,4)*2);const u=(t*.28+hash(j,9))%1,i=Math.floor(u*51),q=pts[i];glow(q[0],q[1],9,p[2],.8)}c.restore()}
function opening(sh,t,p){const lt=t-sh.start,u=clamp(lt/(sh.end-sh.start));backdrop(p,t);const cam={x:Math.sin(u*1.4)*130,y:-410+u*260,z:-220+u*240,roll:-.19+u*.24,f:880};
// Perspective board tiles: history becomes a physical tessellation instead of a diagram.
const objects=[];for(let j=-9;j<=13;j++)for(let i=-12;i<=12;i++){const z=700+j*115,x=i*115;const v=project(x,310,z,cam);if(v)objects.push({i,j,x,z,v})}objects.sort((a,b)=>b.v.z-a.v.z);for(const o of objects){const corners=[[-54,-54],[54,-54],[54,54],[-54,54]].map(([a,b])=>project(o.x+a,310,o.z+b,cam));if(corners.some(x=>!x))continue;const seed=hash(o.i*71+o.j,4),lit=seed>.8&&u>.15;poly(corners.map(q=>[q.x,q.y]),lit?p[1]+'65':((o.i+o.j)%2?'#172b37':'#1b3540'));line([...corners.map(q=>[q.x,q.y]),[corners[0].x,corners[0].y]],p[1]+'30',1);if(seed>.91){const q=project(o.x,296,o.z,cam);ellipse(q.x,q.y,31*q.k,12*q.k,seed>.96?p[2]:'#071118');}}
const k=out(lt/.7),x=970,y=515-90*Math.sin(u*Math.PI);glow(x,y,240,p[1],.38);c.save();c.translate(x,y);c.rotate(-.25+u*.7);ellipse(0,18,166*k,62*k,'#020a12');const g=c.createLinearGradient(-100,-70,100,70);g.addColorStop(0,'#fffef0');g.addColorStop(.4,'#8fdfce');g.addColorStop(1,'#244861');ellipse(0,0,164*k,72*k,g);c.globalAlpha=.8;ellipse(-45,-21,76*k,12*k,'#fff8e0');c.restore();if(u>.3){fan(x,y,240,ease((u-.3)/.5),ease((u-.3)/.5),p,-.5+u);ribbons(t,p,{x,y},10,.4)}dust(t,p,80);if(sh.cast?.length)cast(sh,t,[{x:1300,y:915,h:510,alpha:ease((u-.42)/.2)}]);if(!config.labels){type(sh.label||'从一枚棋子，醒来。',170,180,42,p[2],'left',600);type('AlphaGo',170,237,24,p[1],'left');}vignette(.35)}
function attention(sh,t,p){const lt=t-sh.start,u=clamp(lt/(sh.end-sh.start));backdrop(p,t,sh.palette);const angle=-.8+u*.8;const cx=1050+Math.sin(u*2)*80,cy=710;fan(cx,cy,480,t,ease(u*1.8),p,angle);c.save();c.globalAlpha=.26;fan(cx+20,cy+12,510,t,ease(u*1.8),[p[0],p[1],p[1],p[3]],angle);c.restore();ribbons(t,p,{x:cx,y:530},28,.8);const nodes=[];for(let i=0;i<24;i++){const a=i/24*TAU+u*.45;nodes.push([cx+Math.cos(a)*(360+120*Math.sin(i*3)),510+Math.sin(a)*260])}c.save();for(let i=0;i<24;i++)for(let j=i+1;j<24;j++){if(hash(i*31+j,1)>.91){c.globalAlpha=.12+.2*Math.pow(Math.sin(t*2+i),2);line([nodes[i],nodes[j]],p[2],1)}}c.globalAlpha=1;for(const [x,y]of nodes)glow(x,y,6,p[2],.8);c.restore();cast(sh,t,[{x:560,y:925,h:650},{x:1440,y:950,h:570},{x:1020,y:1000,h:470}]);if(!config.labels)type(sh.label||'注意力，让彼此看见。',155,150,43,p[2],'left');if(sh.term!==false)type('Transformer · 2017',158,210,24,p[1],'left');dust(t,p,100);vignette(.25)}
function future(sh,t,p){const lt=t-sh.start,u=clamp(lt/(sh.end-sh.start));backdrop(p,t);const cx=960,cy=480,flight=lt*530;const rings=[];for(let i=0;i<46;i++){let z=100+(i*180-flight)%8280;if(z<100)z+=8280;rings.push({z,i})}rings.sort((a,b)=>b.z-a.z);c.save();for(const {z,i} of rings){const k=950/z,r=780*k,rot=i*.27+lt*.2;const pts=[];for(let j=0;j<=100;j++){const a=j/100*TAU;const rr=r*(1+.12*Math.cos(a*6+i*.2));pts.push([cx+Math.cos(a+rot)*rr,cy+Math.sin(a+rot)*rr*.62])}c.globalAlpha=clamp(k*.28,0,.8);line(pts,p[i%3?1:3],Math.max(.5,k*1.2));if(i%4===0)for(let j=0;j<12;j++){const a=j/12*TAU+rot;ellipse(cx+Math.cos(a)*r,cy+Math.sin(a)*r*.62,Math.max(1,k*4),Math.max(1,k*4),p[2])}}c.restore();glow(cx,cy,180,p[2],.65);const still=sh.hold||false;seated(sh.cast||[],t,p,(sh.cast||[]).slice(0,2));cast({...sh,cast:(sh.cast||[]).slice(0,2)},t,[{x:640,y:920,h:660},{x:1280,y:890,h:610}]);if(sh.label)type(sh.label,960,140,52,p[2]);const labels=sh.concepts||['AGI','SGI','奇点'];labels.forEach((v,i)=>{const a=i/3*TAU+u*.3;type(v,960+Math.cos(a)*670,510+Math.sin(a)*345,34,p[2])});dust(t,p,90);vignette(.5)}
function fractures(sh,t,p){const lt=t-sh.start,u=clamp(lt/(sh.end-sh.start));backdrop(p,t,sh.palette);const plate=assets.plates[sh.plate];if(plate){c.save();c.globalAlpha=.7;cover(plate);c.restore()}for(let i=0;i<42;i++){const ang=hash(i,7)*TAU,r=hash(i,9)*800,move=out(u)*300;const x=960+Math.cos(ang)*(r+move),y=540+Math.sin(ang)*(r*.6+move);c.save();c.translate(x,y);c.rotate(hash(i,3)*3+u*(hash(i,4)-.5)*2);const w=30+hash(i,1)*160,h=30+hash(i,2)*230;c.globalAlpha=.35+.5*hash(i,6);poly([[-w,-h],[w,-h*.4],[w*.6,h],[-w*.7,h*.7]],p[i%3?2:3]);c.restore()}cast(sh,t);if(sh.label)type(sh.label,960,145,46,p[2]);vignette(.25)}
const pixCanvas=document.createElement('canvas');pixCanvas.width=480;pixCanvas.height=270;const pc=pixCanvas.getContext('2d');
function sailPoint(u,v,t){return{x:960+u*(1130-240*v),y:80+v*275+u*u*90-Math.sin(v*Math.PI)*52+Math.sin(t*.7+u*2)*9}}
function sailMesh(t){const cols=28,rows=7;for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const u=i/cols*2-1,v=j/rows,a=sailPoint(u,v,t),b=sailPoint(u+2/cols,v,t),d=sailPoint(u,v+1/rows,t),e=sailPoint(u+2/cols,v+1/rows,t);const shade=i%2?1:0,blue=i%7===0||i%7===1;const g=c.createLinearGradient(a.x,a.y,e.x,e.y);g.addColorStop(0,blue?(shade?'#39527c':'#223b67'):(shade?'#fff8df':'#d9d0b7'));g.addColorStop(1,blue?'#142b52':(shade?'#c5bda8':'#f8f1d9'));poly([[a.x,a.y],[b.x,b.y],[e.x,e.y],[d.x,d.y]],g);c.save();c.globalAlpha=.07;line([[a.x,a.y],[e.x,e.y]],'#463e2b',1);c.restore()}
for(let i=0;i<=cols;i++){const u=i/cols*2-1,pts=[];for(let j=0;j<=rows;j++){const q=sailPoint(u,j/rows,t);pts.push([q.x,q.y])}line(pts,'#655131',3.5);line(pts,'#d3b574',1.2)}const rim=[];for(let i=0;i<=80;i++){const q=sailPoint(i/80*2-1,1,t);rim.push([q.x,q.y])}line(rim,'#67502f',9);line(rim,'#d8bd7e',3)}
function ensemble(sh,t,p){const u=clamp((t-sh.start)/(sh.end-sh.start)),ids=sh.cast||[];physicalBackground(sh,t,p,'canopy_detail');
// Retain photographed cloth at the top and reveal a cobalt atmosphere below the canopy.
const g=c.createLinearGradient(0,140,0,H);g.addColorStop(0,'#10204400');g.addColorStop(.4,'#183568ce');g.addColorStop(1,'#07162df8');c.fillStyle=g;c.fillRect(0,0,W,H);glow(950,630,600,'#7d9fdf',.15);
if(ids.length<=4){sailMesh(t);cast(sh,t,ids.map((id,i)=>({x:960+(i-(ids.length-1)/2)*640,y:920,h:680})));}
else{c.save();c.translate(960,530);c.rotate(Math.sin(t*.2)*.018);c.translate(-960,-530);sailMesh(t);
const formation=ids.map((id,i)=>{if(i<2)return{id,i,x:i?1320:610,y:975,h:490};const j=i-2,n=ids.length-2,a=-Math.PI*.94+j/Math.max(1,n-1)*Math.PI*1.88;return{id,i,x:960+Math.sin(a)*(740+(j%2)*55),y:695+Math.cos(a)*170,h:160+(Math.cos(a)+1)*45}}).sort((a,b)=>a.y-b.y);
for(const q of formation){const waist={x:q.x,y:q.y-q.h*.49},anchor=sailPoint(clamp((q.x-960)/950,-.98,.98),.94,t);line([[anchor.x-14,anchor.y],[waist.x-10,waist.y]],'#080f26',3.5);line([[anchor.x+14,anchor.y],[waist.x+10,waist.y]],'#d2ae70',1.3);line([[anchor.x-14,anchor.y],[waist.x-10,waist.y]],'#a78b59',1.1);sprite(q.id,q.x,q.y,q.h,t,{cadence:12,seed:q.i,bob:3,angle:Math.sin(t*.8+q.i)*.025,unfold:sh.params?.state==='catch_future'});}
c.restore();}
if(sh.scene==='pixel'){pc.clearRect(0,0,480,270);pc.drawImage(canvas,0,0,480,270);c.save();c.imageSmoothingEnabled=false;c.drawImage(pixCanvas,0,0,W,H);c.restore()}dust(t,p,35);vignette(.22)}
function physicalBackground(sh,t,p,defaultPlate){backdrop(p,t,sh.palette);const img=proceduralBackground||assets.plates[sh.plate||defaultPlate];if(img){c.save();const zoom=1.025+Math.sin(t*.13)*.012;c.translate(960,540);c.scale(zoom,zoom);c.translate(-960,-540);cover(img);c.restore()}return !!img}
function metalSocket(x,y,r,p,t,occupied){c.save();c.translate(x,y);c.rotate(-.10);const g=c.createLinearGradient(0,-r*.3,0,r*.3);g.addColorStop(0,'#efe4b8');g.addColorStop(.28,'#ae8648');g.addColorStop(.55,'#f5d694');g.addColorStop(1,'#533f26');ellipse(0,12,r,r*.25,'#12234b');ellipse(0,0,r,r*.24,g);ellipse(0,-3,r*.82,r*.17,'#071326');c.strokeStyle='#f7e7bc';c.lineWidth=1.5;c.beginPath();c.ellipse(0,-3,r*.86,r*.19,0,Math.PI,TAU);c.stroke();if(occupied){const a=c.createLinearGradient(0,-r*.3,0,r*.1);a.addColorStop(0,'#ffffed');a.addColorStop(.5,'#ded7c5');a.addColorStop(1,'#5772a3');ellipse(0,-r*.065,r*.73,r*.18,a)}c.restore()}
function birth(sh,t,p){const lt=t-sh.start,u=clamp(lt/(sh.end-sh.start)),ids=sh.newCast?.length?sh.newCast:(sh.cast||[]).slice(-1),night=sh.palette!=='day';physicalBackground(sh,t,p,night?'cyber_fan':'go_macro');
// Camera-sized physical stage overlays photographed material. No repeated graphic fan wallpaper.
const shade=c.createLinearGradient(0,250,0,H);shade.addColorStop(0,'#102a5800');shade.addColorStop(1,night?'#05132ddd':'#123064a0');c.fillStyle=shade;c.fillRect(0,0,W,H);
const registry=Object.keys(config.modelNames||{}),prior=(sh.params?.empty||ids.length)-ids.length;
for(let j=0;j<23;j++){if(ids.includes(registry[j]))continue;const a=-Math.PI*.88+j/22*Math.PI*1.76,x=960+Math.sin(a)*820,y=760+Math.cos(a)*145;metalSocket(x,y,26,p,t,j>=prior)}
// Established people remain attached to physical rims in depth, dimmed only by distance.
for(const id of sh.cast||[]){if(ids.includes(id))continue;const n=registry.indexOf(id),a=-Math.PI*.88+n/22*Math.PI*1.76,x=960+Math.sin(a)*820,y=760+Math.cos(a)*145;sprite(id,x,y-20,130,t,{still:true,cadence:12,alpha:.85})}
ids.slice(0,4).forEach((id,i)=>{const four=ids.length===4,img=assets.sprites[id],bodyHeight=four?Math.min(500,540/(img?img.naturalWidth/img.naturalHeight:1)):650,x=960+(i-(ids.length-1)/2)*(four?420:510),y=900,delay=i*.035,open=ease((u-delay)/.46),born=ease((u-.13-delay)/.40);metalSocket(x,y,four?140:170,p,t,born<.08);glow(x,y-100,180,'#8ba9f1',.24*(1-born));
// The seed cracks into solid material leaves while the entire authoritative body appears, never clipped at the head.
for(let j=0;j<18;j++){const a=j/18*TAU-.4,r=45+out(open)*170,xx=x+Math.cos(a)*r,yy=y-80-Math.sin(a)*r*.6-open*180;c.save();c.globalAlpha=(1-born)*.9;c.translate(xx,yy);c.rotate(a+open*1.4);poly([[-16,-48],[20,-18],[9,48],[-24,24]],j%3?'#fff5d9':'#2e4c89');c.restore()}
if(born>0)sprite(id,x,y-42-born*32,bodyHeight,t,{alpha:clamp(born*5),cadence:12,still:true,unfold:sh.params?.state?.includes('unfold')});
for(let j=0;j<44;j++){const age=u-.15-j*.008;if(age<0||age>.6)continue;const a=hash(j,i+8)*TAU,r=age*430;c.globalAlpha=Math.sin(age/.6*Math.PI)*.7;ellipse(x+Math.cos(a)*r,y-120-Math.sin(a)*r*.7-age*220,1+hash(j,8)*3,1+hash(j,8)*3,'#f5d59a')}c.globalAlpha=1;});vignette(.28)}
function reservedTile(sh,t,p){physicalBackground(sh,t,p,'ivory_world');const u=clamp((t-sh.start)/(sh.end-sh.start)),cx=960+Math.sin(u*.7)*8,cy=588;
// Twenty-two distinct empty seats surround the single untouched material source.
const seats=Array.from({length:22},(_,i)=>{const a=i/22*TAU;return{x:960+Math.cos(a)*755,y:635+Math.sin(a)*240,r:25+(Math.sin(a)+1)*8}}).sort((a,b)=>a.y-b.y);
for(const q of seats.filter(q=>q.y<650))metalSocket(q.x,q.y,q.r,p,t,false);
c.save();c.shadowColor='rgba(8,24,47,.22)';c.shadowBlur=35;c.shadowOffsetY=30;ellipse(cx,cy+80,322,72,'rgba(25,43,65,.22)');c.restore();metalSocket(cx,cy+52,340,p,t,false);
c.save();c.translate(cx,cy);c.rotate(-.1);
// The closed ivory cap has thickness, a shaded underside and a quiet sculpted highlight.
const under=c.createLinearGradient(0,-10,0,92);under.addColorStop(0,'#a69b7b');under.addColorStop(.45,'#e6dbc0');under.addColorStop(1,'#6e7890');ellipse(0,24,296,103,under);
const ivory=c.createRadialGradient(-88,-64,10,35,27,328);ivory.addColorStop(0,'#fffef1');ivory.addColorStop(.3,'#fff7df');ivory.addColorStop(.68,'#e0d8bd');ivory.addColorStop(1,'#8e9bb0');ellipse(0,0,298,107,ivory);
c.strokeStyle='rgba(67,82,106,.46)';c.lineWidth=2;c.beginPath();c.ellipse(0,14,294,98,0,.10,Math.PI-.12);c.stroke();c.strokeStyle='rgba(255,255,241,.8)';c.lineWidth=2;c.beginPath();c.ellipse(-3,-3,285,98,0,Math.PI*1.06,Math.PI*1.88);c.stroke();
// Shallow sole impression, still empty: a negative relief rather than a new person.
c.save();c.translate(3,-8);c.rotate(-.16);c.scale(1,.55);c.beginPath();c.moveTo(-102,6);c.bezierCurveTo(-98,-35,-58,-45,-12,-34);c.bezierCurveTo(29,-25,66,-36,99,-12);c.bezierCurveTo(123,9,101,42,67,44);c.bezierCurveTo(23,46,7,19,-27,22);c.bezierCurveTo(-63,30,-102,35,-102,6);const sole=c.createLinearGradient(0,-40,0,45);sole.addColorStop(0,'rgba(85,92,108,.29)');sole.addColorStop(.5,'rgba(147,147,139,.10)');sole.addColorStop(1,'rgba(255,255,242,.42)');c.fillStyle=sole;c.fill();c.strokeStyle='rgba(235,228,204,.7)';c.lineWidth=2;c.stroke();c.restore();c.restore();
for(const q of seats.filter(q=>q.y>=650))metalSocket(q.x,q.y,q.r,p,t,false);vignette(.16)}
function cel(sh,t,p){const qt=Math.floor(t*(sh.cadence||12))/(sh.cadence||12),u=clamp((t-sh.start)/(sh.end-sh.start));c.fillStyle='#eee6d2';c.fillRect(0,0,W,H);
// Two decisive folded planes frame the dancers; one hard shadow establishes paper thickness.
const drift=18*Math.sin(qt*2);poly([[-100,-30],[1320,-30],[720+drift,390],[-100,970]],'#2049a2');poly([[1940,10],[1240,485],[1590,1120],[1940,1120]],'#d6a367');poly([[1940,20],[1275,492],[1630,1120],[1940,1120]],'#fff8e2');line([[-50,1000],[730+drift,415],[1360,-20]],'#7892c1',4);
for(let i=0;i<12;i++){const x=hash(i,4)*W,y=hash(i,8)*H;line([[x,y],[x+30+hash(i,2)*60,y-25]],i%3?'#274ba066':'#c18451',2)}
const ids=sh.cast||[];cast(sh,qt,ids.map((id,i)=>({x:960+(i-(ids.length-1)/2)*560,y:950,h:720,angle:Math.sin(qt*3.1+i)*.025})));if(sh.label)type(sh.label,180,150,48,p[2],'left');vignette(.1)}
function explosion(sh,t,p){const u=clamp((t-sh.start)/(sh.end-sh.start));backdrop(p,t);const burst=out(u),cx=960,cy=515;
for(let i=0;i<260;i++){const a=hash(i,1)*TAU,speed=350+hash(i,3)*1600,r=burst*speed,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r*.65;const size=(1-burst*.7)*(2+hash(i,5)*12);c.save();c.translate(x,y);c.rotate(a+t*hash(i,9));c.globalAlpha=(1-u*.65)*(.3+hash(i,8)*.7);poly([[-size*2,-size],[size*3,0],[-size*1.5,size]],p[i%3?2:3]);c.restore();if(i%5===0){c.globalAlpha=.15;line([[cx+Math.cos(a)*r*.7,cy+Math.sin(a)*r*.65*.7],[x,y]],p[1],1)}}c.globalAlpha=1;for(let j=0;j<5;j++){const rr=burst*(400+j*90);c.globalAlpha=(1-u)*.4;c.strokeStyle=p[j%2?1:3];c.lineWidth=1.5;c.beginPath();c.ellipse(cx,cy,rr,rr*.58,0,0,TAU);c.stroke()}c.globalAlpha=1;glow(cx,cy,260*(1-u)+30,p[2],.6*(1-u));cast(sh,t);if(sh.label)type(sh.label,960,150,54,p[2]);vignette(.3)}
async function seek(video,time){const goal=clamp(time,0,Math.max(0,video.duration-1/1000));if(video.readyState>=2&&Math.abs(video.currentTime-goal)<.0001)return;await new Promise((res,rej)=>{const timer=setTimeout(()=>done(new Error('video seek timeout '+goal)),15000);function done(err){clearTimeout(timer);video.removeEventListener('seeked',ok);video.removeEventListener('error',bad);err?rej(err):res()}const ok=()=>done(),bad=()=>done(new Error('media seek error'));video.addEventListener('seeked',ok,{once:true});video.addEventListener('error',bad,{once:true});video.currentTime=goal});if(video.readyState<2)throw new Error('seek completed without frame')}
async function videoScene(sh,t,p){const v=assets.videos[sh.video];if(!v)throw new Error('Missing video '+sh.video);let local=(sh.sourceStart||0)+(t-sh.start)*(sh.sourceRate??1);if(sh.loop)local=local%v.duration;await seek(v,local);cover(v);const intensity=sh.overlay??.2;if(intensity){c.save();c.globalAlpha=intensity;ribbons(t,p,{x:1100,y:500},8,.6);dust(t,p,55);c.restore()}if(sh.overlayCast&&sh.cast?.length)cast(sh,t);if(sh.label){c.fillStyle='#05101b88';c.fillRect(90,95,Math.min(1000,sh.label.length*47+70),96);type(sh.label,125,143,40,p[2],'left')}vignette(.12)}
function lyric(t){const l=(config.lyrics||[]).find(x=>t>=x.start&&t<x.end);if(!l)return;const alpha=Math.min(out((t-l.start)/.08),out((l.end-t)/.12));c.save();c.globalAlpha=alpha;const size=config.lyricSize||40;c.font=`600 ${size}px "PingFang SC",sans-serif`;const width=c.measureText(l.text).width;const g=c.createLinearGradient(0,H-150,0,H);g.addColorStop(0,'#00000000');g.addColorStop(1,'#000000b0');c.fillStyle=g;c.fillRect(0,H-170,W,170);c.shadowColor='#050915';c.shadowBlur=12;type(l.text,960,H-70,size,'#fffaf0','center',600);c.restore()}
function textBackingBounds(txt,x,y,size,align='left',weight=600){c.font=`${weight} ${size}px "PingFang SC","Noto Sans CJK SC","Microsoft YaHei",sans-serif`;c.textAlign=align;c.textBaseline='middle';const m=c.measureText(txt);return{x:x-m.actualBoundingBoxLeft-12,y:y-m.actualBoundingBoxAscent-12,right:x+m.actualBoundingBoxRight+12,bottom:y+m.actualBoundingBoxDescent+12}}
function navyBacking(b){c.save();c.shadowBlur=0;c.fillStyle='rgba(5,18,43,.86)';c.fillRect(b.x,b.y,b.right-b.x,b.bottom-b.y);c.restore()}
function timedLabels(t,sh){const list=Array.isArray(config.labels)?config.labels:(config.labels?.labels||[]),active=list.filter(l=>{const a=l.start??l.in_frame/(config.fps||60),b=l.end??l.out_frame/(config.fps||60);return t>=a&&t<b}),seen=new Set();let row=0;for(const l of active){if(seen.has(l.text))continue;seen.add(l.text);const x=l.x??135,y=l.y??(145+row*57);c.save();navyBacking(textBackingBounds(l.text,x,y,l.size||34));c.shadowColor='#020611';c.shadowBlur=9;type(l.text,x,y,l.size||34,'#fff9e9','left',600);c.restore();row++}}
function transition(sh,t,p){const d=t-sh.start,mode=sh.transition||'cut';if(d<0||d>.42)return;const k=1-ease(d/.42);if(mode==='shards'){c.save();for(let i=0;i<16;i++){const x=i*135;poly([[x-90*k,-10],[x+230*k,-10],[x+80*k,H+10],[x-120*k,H+10]],p[2])}c.restore()}else if(mode==='iris'){c.save();c.fillStyle=p[0];c.beginPath();c.rect(0,0,W,H);c.ellipse(960,540,(1-k)*1400+.1,(1-k)*800+.1,0,0,TAU);c.fill('evenodd');c.restore()}else if(mode==='flash'){c.save();c.globalAlpha=k*.45;c.fillStyle=p[2];c.fillRect(0,0,W,H);c.restore()}}
async function render(t){t=clamp(Number(t)||0,0,config.duration||43.67);frameTime=t;window.textBoxes=[];c.setTransform(1,0,0,1,0,0);c.globalAlpha=1;c.globalCompositeOperation='source-over';c.shadowBlur=0;const shots=config.shots||[],raw=shots.find(s=>t>=s.start&&t<s.end)||shots[shots.length-1],sh=raw&&config.labels?{...raw,label:'',modelLabels:false,term:false,concepts:[]}:raw;if(!sh){c.fillStyle='#0b1324';c.fillRect(0,0,W,H);type('No configured shots',960,540);return}const p=palettes[sh.palette]||palettes.night;audioReactive=!(sh.scene==='video'||sh.video);proceduralBackground=null;if(sh.bgVideo){const bg=assets.videos[sh.bgVideo];if(!bg)throw new Error('Missing background video '+sh.bgVideo);await seek(bg,(sh.bgSourceStart||0)+(t-sh.start)*(sh.bgSourceRate??1));proceduralBackground=bg}c.save();if(sh.scene==='video'||sh.video)await videoScene(sh,t,p);else if(sh.scene==='opening')opening(sh,t,p);else if(sh.scene==='attention')attention(sh,t,p);else if(sh.scene==='future')future(sh,t,p);else if(sh.scene==='fractures'||sh.scene==='paper')fractures(sh,t,p);else if(sh.scene==='birth')birth(sh,t,p);else if(sh.scene==='fan'){if(sh.params?.state==='last_oval')reservedTile(sh,t,p);else attention(sh,t,p);}else if(sh.scene==='cel')cel(sh,t,p);else if(sh.scene==='explosion')explosion(sh,t,p);else ensemble(sh,t,p);c.restore();transition(sh,t,p);timedLabels(t,sh);if(!sh.hideLyrics)lyric(t);if(sh.brand||t>(config.duration||43.67)-1.6){c.save();c.globalAlpha=ease(((config.duration||43.67)-t<1.6? t-((config.duration||43.67)-1.6):1)/.5);const tb=textBackingBounds('先别落地',960,350,58,'center',600),bb=textBackingBounds('AI SI - I',960,412,27,'center',500);navyBacking({x:Math.min(tb.x,bb.x),y:tb.y,right:Math.max(tb.right,bb.right),bottom:bb.bottom});type('先别落地',960,350,58,'#fff8e9','center',600);type('AI SI - I',960,412,27,'#fff8e9','center',500);c.restore()}grain(t);window.lastFrame={t,shot:sh.id,errors:[...errors]}}
window.ready=(async()=>{const r=await fetch(cfgURL);if(!r.ok)throw new Error('Config '+r.status);config=await r.json();for(const band of ['mix','low','high']){const env=[...(config.audioFeatures?.rms_envelopes?.[band]||[])].sort((a,b)=>a-b),hits=(config.audioFeatures?.onsets?.[band]||[]).map(x=>x[1]).sort((a,b)=>a-b);audioScales[band]={envelope:env[Math.floor(env.length*.95)]||1,attack:hits[Math.floor(hits.length*.95)]||1}}if(config.strictAssets){for(const sh of config.shots||[]){for(const id of sh.cast||[])if(!config.sprites?.[id])throw new Error('Missing configured sprite '+id);if(sh.video&&!config.videos?.[sh.video])throw new Error('Missing configured video '+sh.video)}}await document.fonts.ready;const tasks=[];for(const kind of ['sprites','plates'])for(const [id,v]of Object.entries(config[kind]||{}))tasks.push(new Promise((res,rej)=>{const img=new Image();img.onload=()=>{assets[kind][id]=img;res()};img.onerror=()=>rej(new Error('Image load '+id));img.src=resolveAsset(v)}));for(const [id,v]of Object.entries(config.videos||{}))tasks.push(new Promise((res,rej)=>{const el=document.createElement('video');el.muted=true;el.preload='auto';el.playsInline=true;el.onloadeddata=()=>{assets.videos[id]=el;res()};el.onerror=()=>rej(new Error('Video load '+id));el.src=resolveAsset(v);el.load()}));await Promise.all(tasks);window.filmConfig=config;window.assetStatus={videos:Object.keys(assets.videos),sprites:Object.keys(assets.sprites),plates:Object.keys(assets.plates)};return true})();window.renderFrame=async t=>{await window.ready;return render(t)};
