#!/usr/bin/env node
import puppeteer from '../../../../tools/web/node_modules/puppeteer-core/lib/puppeteer/puppeteer-core.js';
import {createServer} from 'node:http';import {createReadStream,statSync,mkdirSync,writeFileSync} from 'node:fs';import {resolve,dirname,extname,relative} from 'node:path';import {spawn} from 'node:child_process';import {once} from 'node:events';
const args=process.argv.slice(2),opt=(k,d)=>{const i=args.indexOf('--'+k);return i<0?d:args[i+1]};
const root=resolve(opt('root','.')),config=resolve(opt('config','episodes/first-day-mix/production/config.json')),out=resolve(opt('out','work/first-day-mix/film-silent.mp4'));
const fps=Number(opt('fps',60)),from=Number(opt('from',0)),to=Number(opt('to',43.67)),frames=Math.ceil(to*fps)-Math.ceil(from*fps),stills=opt('stills',null);
const mime={'.html':'text/html','.js':'text/javascript','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.mp4':'video/mp4','.webm':'video/webm','.wav':'audio/wav'};
const server=createServer((req,res)=>{try{const p=resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(relative(root,p).startsWith('..')){res.writeHead(403).end();return}const st=statSync(p),range=req.headers.range;res.setHeader('Content-Type',mime[extname(p)]||'application/octet-stream');res.setHeader('Accept-Ranges','bytes');if(range){const m=/bytes=(\d+)-(\d*)/.exec(range),start=Number(m[1]),end=m[2]?Math.min(Number(m[2]),st.size-1):st.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${st.size}`,'Content-Length':end-start+1});createReadStream(p,{start,end}).pipe(res)}else{res.writeHead(200,{'Content-Length':st.size});createReadStream(p).pipe(res)}}catch(e){res.writeHead(404).end(String(e))}});server.listen(0,'127.0.0.1');await once(server,'listening');
let browser,ff;try{browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--hide-scrollbars','--force-color-profile=srgb','--font-render-hinting=none','--autoplay-policy=no-user-gesture-required','--disable-background-timer-throttling']});const page=await browser.newPage();await page.setViewport({width:1920,height:1080,deviceScaleFactor:1});page.on('pageerror',e=>console.error('PAGE',e.message));const base=`http://127.0.0.1:${server.address().port}/`,cfg=relative(root,config).split('\\').join('/');await page.goto(base+'episodes/first-day-mix/production/renderer/index.html?config='+encodeURIComponent('/'+cfg),{waitUntil:'load'});await page.evaluate(async()=>await window.ready);console.log('Assets',await page.evaluate(()=>window.assetStatus));mkdirSync(dirname(out),{recursive:true});
if(stills){mkdirSync(out,{recursive:true});for(const t of stills.split(',').map(Number)){await page.evaluate(async t=>await window.renderFrame(t),t);await page.screenshot({path:resolve(out,`frame-${t.toFixed(3)}.png`)});console.log('Still',t)}}else{
ff=spawn('ffmpeg',['-y','-v','error','-f','image2pipe','-framerate',String(fps),'-i','pipe:0','-an','-c:v','libx264','-preset',opt('preset','fast'),'-crf',opt('crf','17'),'-pix_fmt','yuv420p','-vf','scale=out_color_matrix=bt709','-color_primaries','bt709','-color_trc','bt709','-colorspace','bt709','-movflags','+faststart',out],{stdio:['pipe','inherit','inherit']});const ended=once(ff,'close');ff.stdin.on('error',e=>console.error('ffmpeg pipe',e.message));const begin=Date.now();for(let i=0;i<frames;i++){const t=(Math.ceil(from*fps)+i)/fps;await page.evaluate(async t=>await window.renderFrame(t),t);const buf=await page.screenshot({type:'png'});if(!ff.stdin.write(buf))await once(ff.stdin,'drain');if(i%60===0)console.log(`${i}/${frames} t=${t.toFixed(3)} elapsed=${((Date.now()-begin)/1000).toFixed(1)}s`)}ff.stdin.end();const [code]=await ended;if(code!==0)throw new Error('ffmpeg exit '+code);writeFileSync(out+'.json',JSON.stringify({from,to,fps,frames,firstFrame:Math.ceil(from*fps),duration:frames/fps,config},null,2)+'\n');console.log('Rendered',frames,'frames',out)}
}finally{if(browser)await browser.close();server.close();if(ff&&!ff.killed&&ff.exitCode===null)ff.kill('SIGTERM')}
